bullet-train-co/bullet_train-core

bullet_train/lib/tasks/bullet_train_tasks.rake
Closes #39.
JavaScript changes weren't being reflected in the browser when watching multiple npm packages in parallel, so I simplified the script and made it so we can only watch one npm package at a time.
The downside is that developers can only adjust the JavaScript for the package that they're watching. This is the same as what we were doing before we migrated to `bullet_train-core` when using `bin/develop`, so I'd rather fall back to that interface if it's what developers are already expecting.
We also have the commit history if we ever want to try running the processes in parallel again, but as I mentioned in the issue, I don't think it's worth the effort right now (maybe if we get developers saying they're having a hard time trying to develop in JS files across packages).
=> Watch JS serially in `bin/hack`

bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/limits/_form.html.erb, bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/limits/_index.html.erb, bullet_train/app/models/billing/mock_limiter.rb
This PR fixes an issue where adding the [bullet_train-billing-usage gem](https://github.com/bullet-train-pro/bullet_train-billing-usage) and following all of the instructions did not render the broken limits for products.
This allowed a user to add a resource to a hard-enforced product limit through the interface.
The issue is that BT is not rendering the correct partials from the gem and just using the one found in [bullet_train-themes-tailwind_css](https://github.com/bullet-train-co/bullet_train-core/tree/main/bullet_train-themes-tailwind_css). I am unsure yet why BT is not rendering the partial from the billing-usage gem but it may be because it is part of the BT pro gem.
In order to fix this for now, the views for the index and the form from the billing-usage gem were copied to the …
=> Fix Billing Usage Limits Integration

.standard.yml, Gemfile.lock, bullet_train-fields/app/helpers/fields_helper.rb, bullet_train/app/helpers/attributes_helper.rb
The Standard gem was previously v1.19.1 and didn't pick up on some Standard Ruby failures.
I updated the gem to v1.20.0 and made the fixes.
We had this line in `bullet_train-outgoing_webhooks/app/models/concerns/webhooks/outgoing/uri_filtering.rb`:
```ruby
rescue IPAddr::InvalidAddressError, ArgumentError # standard:disable Lint/ShadowedException
```
Since the comment to disable this check was there, I decided to add this to `.standard.yml`. I added it under the set of files under the TODO in `.standard.yml` just in case we need to look over it again and adjust this line accordingly.
I remember this being unfavorable way back before the Great Unbundling, so I just wanted to bring it up in case we wanted to remove this or handle it in another way.
=> Update the Ruby Standard gem

bullet_train-api/app/controllers/api/open_api_controller.rb, bullet_train-api/app/controllers/concerns/api/v1/users/controller_base.rb, bullet_train-outgoing_webhooks/app/controllers/api/v1/webhooks/outgoing/events_controller.rb, bullet_train-outgoing_webhooks/app/views/api/v1/open_api/index.yaml.erb, bullet_train-outgoing_webhooks/app/views/api/v1/webhooks/outgoing/events/_event.json.jbuilder, bullet_train-outgoing_webhooks/app/views/api/v1/webhooks/outgoing/events/index.json.jbuilder, bullet_train-outgoing_webhooks/app/views/api/v1/webhooks/outgoing/events/show.json.jbuilder, bullet_train-outgoing_webhooks/config/locales/en/webhooks/outgoing/events.en.yml, bullet_train-outgoing_webhooks/config/routes.rb
Kinda closes https://github.com/bullet-train-co/bullet_train-outgoing_webhooks/issues/15
After discussion with @andrewculver we made a conclusion that endpoints information cannot be placed into OpenAPI docs as they're different from Team to Team. What we can do is give information about what's being sent to webhook (payload of `Webhooks::Outgoing::Event` object). So here we add to urls in API just to show those events:
```
/api/v1/teams/:team_id/webhooks/outgoing/events
/api/v1/webhooks/outgoing/events/:id
```
Also `bullet_train-api` now checks if a controller has `:create` or `:update` actions and only then generates corresponding `...Parameters` block in OpenAPI. It also implements _empty_ `update` action for `Api::V1::Users::ControllerBase` so that it has `UserParameters` section in …
=> Add Webhooks::Outgoing::Events to API

bullet_train-api/app/controllers/api/open_api_controller.rb
Fetching the list of gem paths from bundler takes quite a while and when there are more than a few automatic_components_for calls are made, this can cause the server to timeout.
This caches the result for use between calls.
=> Memoize gem paths for creating 'automatic_components_for'

bullet_train-super_scaffolding/Gemfile
I added this specific branch in the Gemfile in [this PR](https://github.com/bullet-train-co/bullet_train-super_scaffolding/pull/79) to prove that the tests were passing, but since we aren't splitting PRs across multiple repositories like before I don't think we'll need this here.
=> Remove unneeded branch from Gemfile

bullet_train/app/views/devise/passwords/edit.html.erb
Adding class - `form` to the form tag fixes the proper spacing issue between form fields
Fixes https://github.com/bullet-train-co/bullet_train-core/issues/4
After fix:
=> Make sure password edit form has `form` class

bullet_train-api/app/views/account/platform/access_tokens/_index.html.erb, bullet_train-themes/app/views/themes/base/attributes/_date.html.erb, bullet_train-themes/app/views/themes/base/attributes/_date_and_time.html.erb
Moving the PR from https://github.com/bullet-train-co/bullet_train-themes/pull/20 to here.
Again, here's how it looks like in the browser:
=> Add default message for token's `last_used_at` attribute

bullet_train/app/controllers/turbo_devise_controller.rb
Closes #99.
@adampal found out that the gem that was giving us trouble is [responders](https://github.com/heartcombo/responders)
The TurboDeviseController fix we have in place is a fix I saw in multiple places:
[Example 1](https://betterprogramming.pub/devise-auth-setup-in-rails-7-44240aaed4be)
[Example 2](https://gorails.com/forum/how-to-use-devise-with-hotwire-turbo-js-discussion#forum_post_17983)
[Example 3](https://qiita.com/jnchito/items/48db78c465493837c41f)
However, it is outdated because `rendering_options` was removed from the repository.
[rendering_options](https://github.com/Edouard-chin/responders/blob/c44dd4fd7107bc82b606384ea2fb602904b586d6/lib/action_controller/responder.rb#L301) was initially added in [this PR](https://github.com/heartcombo/responders/pull/176) and looked …
=> Update TurboDeviseController fix

bullet_train-super_scaffolding/lib/scaffolding/transformer.rb
Revisiting https://github.com/bullet-train-co/bullet_train-super_scaffolding/issues/63
Reading through the Rails docs, it looks like the two most common situations to use `class_name` are:
1. ([docs](https://guides.rubyonrails.org/association_basics.html#self-joins)) When you want to use a specific class for an attribute, but want to give the attribute itself a custom name
2. ([docs](https://guides.rubyonrails.org/association_basics.html#controlling-association-scope)) When the attribute lives in a different namespace
The situation we're handling here is the second one.
In the `if` statement I used here, we simply check if the entire model name is namespaced. It's simple, but I think this it's enough to check if we need to add `class_name` to the attribute in the parent model.
```
> rails …
```
=> Add `class_name` to attribute when model is namespaced

bullet_train-super_scaffolding/lib/scaffolding/file_manipulator.rb, bullet_train-super_scaffolding/lib/scaffolding/oauth_providers.rb, bullet_train-super_scaffolding/lib/scaffolding/transformer.rb
I don't think we need these anymore because we have all of the gems in one place now, as opposed to when they were all each within their own repository (`bullet_train-super_scaffolding`, `bullet_train-api`, etc.)
I ran the Super Scaffolding tests and the OAuth provider scaffolder and everything ran fine.
I'm not sure where the scripts were failing last time, so if there are certain commands you want me to test this with, just let me know!
=> Delete `silence_logs?` definitions outside of `lib/bullet_train.rb`

bullet_train-super_scaffolding/lib/scaffolding/routes_file_manipulator.rb, bullet_train-super_scaffolding/test/lib/scaffolding/routes_file_manipulator_test.rb
* This adds a new method to the RouteFileManipulator class called add_concern_at_line. This method allows you to add a concern to an existing resource.  It is used by the Bullet Train Pro audit_log gem.
=> Update the RouteFileManipulator so it can add concerns to existing routes

bullet_train-super_scaffolding/lib/scaffolding/transformer.rb
Closes #97.
This will ensure we don't get duplicate variable names in Super Scaffolded index partials (specifically on line 2 with the current code we have):
```erb
<%# Before %>
<% team = @team || @team %>
<%# After %>
<% team = @team %>
```
It also ensures that the two variables are properly scaffolded when the model's parent is namespaced (for example, `Objective` which belongs to `Projects::Step`):
```erb
<%# In `app/views/account/objectives/_index.html.erb` %>
<% projects_step = @projects_step || @step %>
```
Also, I'm not sure why but I'm getting the same test failure here as I'm getting in #96 in CircleCI only although the two PRs seem completely unrelated:
```
NameError: undefined local variable or method `rendering_options' for …
```
=> Prevent duplicate variable generation in Super Scaffolded index partials

bullet_train/app/views/layouts/docs.html.erb
Causing a Rails error on the documentation site.
The fix should make the url
https://bullettrain.co/docs/application-options.md
and not
https://bullettrain.co/docs/docs/application-options.md
=> Application-options.md url was missing a /

bullet_train-api/lib/bullet_train/api.rb, bullet_train-api/lib/tokens_controller.rb
Joint PR:
- https://github.com/bullet-train-co/bullet_train/pull/639
As far as I can tell the monkey patched class isn't included until we require it in the `set_configuration` method I wrote here, but if we want to handle this in a different way I can think over another way to load the class.
I've also written more details in the Joint PR, so feel free to check out the information there too.
=> Extract doorkeeper config in starter repository to `bullet_train-api`

bullet_train-super_scaffolding/lib/scaffolding/transformer.rb
Closes https://github.com/bullet-train-co/bullet_train/issues/634.
I suppressed the error here because the `User` model doesn't have a show page that we need to scaffold to. I also saved the value to a variable explicitly first so we know WHY we're suppressing the error, instead of just writing it like this:
```ruby
suppress_could_not_find: child == "User"
```
Unit tests fail without a problem, but this doesn't work with devise, and even if we try to save the new crud field on the Account Details page, it won't persist to the database.
I'm assuming this is because we need to register any custom parameters we want to use for registration, etc.
From the devise docs:
```ruby
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: …
```
=> Suppress error for show page which doesn't exist

bullet_train-api/app/controllers/api/open_api_controller.rb
Addresses the TODO about writing file field attributes in the Open API documentation.
Rails models have `attachment_reflections`, a method in which the return value's first key is the name of the attribute which has the reflection:
```ruby
pry(#<#<Class:0x00007fec00d6f5a8>>)> model.attachment_reflections
=> {"file_field_value"=>
#<ActiveStorage::Reflection::HasOneAttachedReflection:0x00007febfbc9b050
@active_record=
Scaffolding::CompletelyConcrete::TangibleThing(id: integer, absolutely_abstract_creative_concept_id: integer, text_field_value: string, button_value: string, cloudinary_image_value: string, date_field_value: date, email_field_value: string, password_field_value: string, phone_field_value: string, super_select_value: string, text_area_value: text, created_at: datetime, …
```
=> Write file attributes in Open API documentation

bullet_train-super_load_and_authorize_resource/app/controllers/concerns/loads_and_authorizes_resource.rb
Closes #79.
The reason this was breaking for the OAuth account show page was because we were trying to pull a `team` association from either the `@child_object` or `@parent_object` here:
https://github.com/bullet-train-co/bullet_train-core/blob/fab77efab57126c083e0041f97c0e716560a2ffe/bullet_train-super_load_and_authorize_resource/app/controllers/concerns/loads_and_authorizes_resource.rb#L11
However, the `@child_object` is an `Account::Oauth::` object, and the `@parent_object` is a `User`, neither of which have `team`:
```
> @child_object
=> #<Oauth::SpotifyAccount:0x00007ff959c8e060
id: 1,
uid: "gazayas",
data:
{"uid"=>"gazayas",
"info"=>
{"name"=>"gazayas",
...
```
`User` records have a `current_team`, but I didn't want to edit the code to work only when `@parent_object` is a `User` …
=> Set `@team` to `nil` when loading resources with no association to a team

bullet_train/lib/tasks/bullet_train_tasks.rake
Closes #80.
`bin/hack --link` was only linking gems to `local/bullet_train-core` for ones that were already present in the Gemfile. However, these aren't present in the starter repository's Gemfile, so they weren't getting linked:
1. bullet_train-fields
2. bullet_Train-has_uuid
3. bullet_train-scope_validator
4. bullet_train-super_load_and_authorize_resource
5. bullet_train-themes-tailwind_css
With this PR, `bin/hack --link` tags these gems on to the end of the Gemfile, and `bin/hack --reset` removes them completely.
=> Ensure all gems are linked with `bin/hack --link`

bullet_train-super_scaffolding/lib/scaffolding/block_manipulator.rb, bullet_train-super_scaffolding/lib/scaffolding/file_manipulator.rb, bullet_train-super_scaffolding/lib/scaffolding/transformer.rb
```
rails g model Foo team:references title:string && \
bin/super-scaffold crud Foo Team title:text_field --sidebar="ti.ti-world" && \
rails g model Bar foo:references title:string && \
bin/super-scaffold crud Bar Foo,Team title:text_field && \
rails g model Baz bar:references title:string && \
bin/super-scaffold crud Baz Bar,Foo,Team title:text_field
```
When Super Scaffolding a model directly off of `Team`, `@foo` gets scaffolded as a factory to the API controller `setup` method like this:
```ruby
class Api::V1::FoosControllerTest < Api::Test
def setup
super
@foo = build(:foo, team: @team)
@other_foos = create_list(:foo, 3)
```
However, for any nested models, the variables don't get indented properly:
```ruby
def setup
super
@foo = create(:foo, team: @team)
@bar = create(:bar, foo: …
```
=> Fix spacing in Super Scaffolded API test setup

bullet_train-integrations/app/controllers/concerns/account/oauth/omniauth_callbacks/controller_base.rb
Closes #71.
Our OAuth sign up/sign in workflow was failing because the method `handle_outstanding_invitation` hadn't been migrated to `bullet_train-core`.
I also decided to add the method directly to this file as a private method instead of via a helper like before because this is the only place where the method appears.
I was able to invite a new user and sign up with Spotify, so this one should be good to go.
=> Handle invitation for invited user signing up with omniauth

bullet_train/app/views/devise/sessions/new.html.erb
This pull request that we merged recently sets Turbo to `false` for all oauth-related requests: https://github.com/bullet-train-co/bullet_train-base/pull/102
However, this was causing issues when trying to login with two-factor authentication.
When trying to login with 2FA, we get the following error when entering an email and clicking "Next":
```
Completed 406 Not Acceptable in 132305ms (ActiveRecord: 13.5ms | Allocations: 103247)
ActionController::UnknownFormat (ActionController::UnknownFormat):
actionpack (7.0.4) lib/action_controller/metal/mime_responds.rb:217:in `respond_to'
local/bullet_train-core/bullet_train/app/controllers/concerns/sessions/controller_base.rb:9:in `pre_otp'
```
Afterwards, we get redirected back to the same page we were on.
After prying into …
=> Temporarily disable Turbo in new session form

bullet_train/app/models/concerns/users/base.rb, bullet_train/lib/bullet_train.rb
Found by @eadz and also mentioned in https://github.com/bullet-train-co/bullet_train/pull/519#issuecomment-1340037608
I've decided to not consider backwards compatibility here because of [this comment](https://github.com/bullet-train-co/bullet_train/pull/519#issuecomment-1339992627), but we can use the following like @eadz suggested if we want to check for either the old environment variable or the Rails 7 credentials value:
```ruby
ENV['TWO_FACTOR_ENCRYPION_KEY'].present? || Rails.application.credentials.active_record_enc
ryption.present?
```
We still need to fix the turbo-related issue, but for now you can refer to #50 if you want to test out the logic manually in the browser.
=> Enable 2FA automatically when credentials are set

bullet_train-super_scaffolding/lib/scaffolding/transformer.rb
We currently Super Scaffold the [_menu_item.html.erb](https://github.com/bullet-train-co/bullet_train-core/blob/main/bullet_train-super_scaffolding/app/views/account/scaffolding/completely_concrete/tangible_things/_menu_item.html.erb) partial for models that aren't directly scoped off of a Team. For example:
```
> rails g model Bar foo:references title:string
> bin/super-scaffold crud Bar Foo,Team title:text_field
```
However, we tell the developers when Super Scaffolding directly off of `Team` (or nothing) that only these models are eligible for adding a menu item to their navigation bar:
https://github.com/bullet-train-co/bullet_train-core/blob/7cf007def6104e2f95a445e218f76148ce249db1/bullet_train-super_scaffolding/lib/scaffolding/transformer.rb#L1532
Even if it's not used, I think …
=> Skip menu item scaffolding for non-top-level models

bullet_train/bullet_train.gemspec, bullet_train/lib/bullet_train.rb, bullet_train/lib/colorizer.rb
https://github.com/bullet-train-co/bullet_train/issues/577
We get different profile image colors when we are restarting the application as we were using the String Hash method to get the hash of the email which produces different results for different instances. 
As a solution, I used [xxhasg](https://github.com/nashby/xxhash) gem to get the hash of the email which is consistents
=> Fix Profile Image Background Color

bullet_train-super_scaffolding/lib/scaffolding/transformer.rb
Closes https://github.com/bullet-train-co/bullet_train/issues/428
Previously https://github.com/bullet-train-co/bullet_train-super_scaffolding/pull/80
I wanted to use `RoutesFileManipulator#apply` to add the routes, but since we're using `draw`, I don't think we'll be able to scaffold the routes properly with it because `apply` depends on parent blocks. We've already written the proper routes within the new custom namespace file, so I just added the `draw` lines to each original routes file.
```
> rails g model Job team:references title:string
> bin/super-scaffold crud Job Team title:text_field --namespace=client
```
```ruby
Rails.application.routes.draw do
draw "concerns"
draw "devise"
draw "sidekiq"
draw "client"
...
end
```
```ruby
collection_actions = [:index, :new, :create] # …
```
=> Ensure custom namespace routes are scaffolded properly

bullet_train-fields/app/javascript/controllers/fields/file_item_controller.js, bullet_train-fields/app/javascript/controllers/index.js, bullet_train-super_scaffolding/lib/scaffolding/transformer.rb, bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/attributes/_files.erb, bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/fields/_file_field.html.erb
Fixes https://github.com/bullet-train-co/bullet_train-fields/issues/43
super-scaffold can be used as follows to add multiple file attachments.
```
bin/super-scaffold crud-field Project images:file_field{multiple}
```
To support the selective removal of attachments we had to use an array to pass the attachment ids, This adds `#{name}_removal: []` to strong params.
Rails by default replace all the attachments with new ones, We are overriding the active storage method (`def #{name}=(attachables)`) to avoid this and ensure rails persist in existing attachments while adding new ones. 
Note - 
@andrewculver Cosmetic changes like UI design of multi-file upload are not part of this PR, Let me know how it feels and if any changes are necessary.
=> Adds multiple file upload

bullet_train-api/app/controllers/concerns/api/v1/users/controller_base.rb
Moving https://github.com/bullet-train-co/bullet_train-api/pull/32 over here.
I used I18n in response to the review in that PR.
I had to edit the code a little bit now that we have OpenAPI, because when creating the documentation the `params` object becomes a `BulletTrain::Api::StrongParametersReporter`. Just to be safe, I added all of the fields to the to the strong parameters when that's the case.
=> Define User strong parameters based on attributes being updated

bullet_train-themes/app/views/themes/base/attributes/_number.html.erb, bullet_train-themes/app/views/themes/base/fields/_number_field.html.erb
Number fields are added. The options have to be added into the `options` hash for now as the `in` is a keyword gets a little harder to initialize.
Also adds number as an attribute, just like text.
=> Feature: adds number as a possible input and attribute

bullet_train-themes-light/app/views/themes/light/_team.html.erb, bullet_train/app/views/account/teams/_team.html.erb
Goal of this change is to create a team component and move all of the styling from bullet_train/app/views/account/teams/_team.html.erb into the component.
I've just learned about Nice Partials as part of this change (like this concept! as a lightweight to ViewComponent) so feel free to suggest corrections to how I've done the 'slots' and 'locals', made my best guesses here!
I also updated the dark bg color as it looked a little 'light'. Here is a pic of before and after, feel free to revert if the original shade was intentional. I have no strong opinions about design 😅 
Before:
After:
Closes https://github.com/bullet-train-co/bullet_train-core/issues/87
=> Extract team index item into a theme component partial

bullet_train-super_scaffolding/lib/scaffolding/transformer.rb
Closes https://github.com/bullet-train-co/bullet_train/issues/623.
This PR ensures the ability line is only written once when Super Scaffolding the model in question.
=> Prevent duplicate lines in `roles.yml`

bullet_train-outgoing_webhooks/app/controllers/api/v1/webhooks/outgoing/endpoints_controller.rb, bullet_train-outgoing_webhooks/app/controllers/api/v1/webhooks/outgoing/events_controller.rb, bullet_train-outgoing_webhooks/app/views/api/v1/webhooks/outgoing/endpoints/_endpoint.json.jbuilder
Required to support apps that use an endpoint parent other than team
=> Use parent_association setting rather than hardcoded team

bullet_train/lib/tasks/bullet_train_tasks.rake
```
> bin/hack --link 1.2.14
```
Gemfile:
```ruby
gem "bullet_train", "1.2.14"
gem "bullet_train-super_scaffolding", "1.2.14"
gem "bullet_train-api", "1.2.14"
gem "bullet_train-outgoing_webhooks", "1.2.14"
gem "bullet_train-incoming_webhooks", "1.2.14"
gem "bullet_train-themes", "1.2.14"
gem "bullet_train-themes-light", "1.2.14"
gem "bullet_train-integrations", "1.2.14"
gem "bullet_train-integrations-stripe", "1.2.14"
gem "bullet_train-sortable", "1.2.14"
gem "bullet_train-scope_questions", "1.2.14"
gem "bullet_train-obfuscates_id", "1.2.14"
```
Compatible with the `--reset` flag
```
> bin/hack --reset
```
=> Specify package versions with `bin/hack`

bullet_train-super_scaffolding/lib/scaffolding/transformer.rb
When using `TARGET` without `OTHER_TARGETS` for Super Scaffolding, we get the following error:
```
> TARGET=local/bullet_train-core/bullet_train bin/super-scaffold crud-field Membership detail:text_field
rake aborted!
NoMethodError: undefined method `split' for nil:NilClass
/home/gazayas/work/bt/bullet_train/local/bullet_train-core/bullet_train-super_scaffolding/lib/scaffolding/transformer.rb:195:in `resolve_target_path'
```
This fix just skips checking for other targets when the variable is `nil`.
=> Skip `OTHER_TARGETS` when it is `nil`

bullet_train/app/views/account/teams/_form.html.erb
We can add a crud-field to a Team like this:
```
> rails g migration add_detail_to_teams detail:string
> bin/super-scaffold crud-field Team detail:text_field
```
However, we already have a super scaffolding hook here in the starter repository which adds a new field to the Teams form:
https://github.com/bullet-train-co/bullet_train/blob/d4499407e552123c99495ad06d48e98f93fb4b68/app/views/account/teams/_fields.html.erb#L1
This caused the attribute to be doubled on the form.
Deleting the hook here ensures the attribute just shows up once on the form, and now looks like this:
=> Delete unneeded Super Scaffolding hook

bullet_train-super_scaffolding/lib/scaffolding/file_manipulator.rb, bullet_train-super_scaffolding/lib/scaffolding/transformer.rb
In https://github.com/bullet-train-pro/bullet_train-action_models/pull/46 we were trying to remove a `has_one` association from a model like this:
```ruby
scaffold_replace_line_in_file(
"./app/models/scaffolding/completely_concrete/tangible_things/foo.rb",
"",
"has_one :team, through: :team",
)
```
`""` becomes a variable called `content`, and since we have the following `if` statement in the [FileManipulator](https://github.com/bullet-train-co/bullet_train-core/blob/0680b1f48fd32b88648a189c43a88109d324df36/bullet_train-super_scaffolding/lib/scaffolding/file_manipulator.rb#L26), it's skipping the file update altogether:
```ruby
if target_file_content.include?(content)
puts "No need to update '#{file}'. It already has '#{content}'."
else
puts "Updating '#{file}'." unless silence_logs? …
```
=> Skip updating for content that already exists and has been transformed

.circleci/config.yml, .circleci/matching_branch_check, Gemfile, Gemfile.lock, bin/checkout-and-link-starter-repo
Joint PR
- https://github.com/bullet-train-co/bullet_train/pull/690
There was a CI bug which we fixed by merging https://github.com/bullet-train-co/bullet_train/pull/649/files in the starter repository.
However, even though we have `- checkout` right after `steps:` here in the CI config file, it looks like this doesn't quite work when updating to the new CI image, `cimg/ruby:3.2.1-browsers`.
The problem is that there is a file in `tmp/starter`, our working directory. The file is `LICENSE.chromedriver`, and we can't use `git clone` until the working directory is empty.
I just simply deleted the file before cloning. (Check comment [here](https://github.com/CircleCI-Public/browser-tools-orb/issues/62#issuecomment-1377819007))
Since people who submit PRs to the starter repository have their …
=> Ruby 3.2.1

bin/checkout-and-link-starter-repo
Reverts a change made in #179 to fetch from people's forks, since the code will fail for bullet_train-core PRs submitted by contributors where they don't have a fork of the bullet_train starter repo i.e. we're subtly requiring that they do.
cc @gazayas
=> Fetch from main repo, avoid forks for now

bullet_train-api/test/integration/navigation_test.rb, bullet_train-fields/test/integration/navigation_test.rb, bullet_train-has_uuid/test/integration/navigation_test.rb, bullet_train-incoming_webhooks/test/integration/navigation_test.rb, bullet_train-integrations-stripe/test/integration/navigation_test.rb, bullet_train-integrations/test/integration/navigation_test.rb, bullet_train-obfuscates_id/test/integration/navigation_test.rb, bullet_train-outgoing_webhooks/test/integration/navigation_test.rb, bullet_train-scope_questions/test/integration/navigation_test.rb, bullet_train-sortable/test/integration/navigation_test.rb, bullet_train-super_load_and_authorize_resource/test/integration/navigation_test.rb, bullet_train-super_scaffolding/test/integration/navigation_test.rb, bullet_train-themes-light/test/integration/navigation_test.rb, bullet_train-themes-tailwind_css/test/integration/navigation_test.rb, bullet_train-themes/test/integration/navigation_test.rb, bullet_train/test/integration/navigation_test.rb
Just clutters up the test directory since we're not using them.
=> Remove empty navigation_test.rb files

bullet_train-themes-light/app/views/showcase/previews/partials/_notices.html.erb, bullet_train-themes-light/app/views/showcase/previews/partials/_page.html.erb
Our page showcase says we render "shared/notices" but we don't demo that there — instead it's demoed on the notices preview.
Seems like it's clearer on the page preview, so I'm moving it there.
I've also spruced up the description HTML to look a little nicer.
=> Showcase page with notices on its preview

bullet_train/lib/tasks/bullet_train_tasks.rake
```
bin/hack --link github
```
```ruby
gem "bullet_train", git: 'http://github.com/bullet-train-co/bullet_train-core.git'
gem "bullet_train-super_scaffolding", git: 'http://github.com/bullet-train-co/bullet_train-core.git'
gem "bullet_train-api", git: 'http://github.com/bullet-train-co/bullet_train-core.git'
gem "bullet_train-outgoing_webhooks", git: 'http://github.com/bullet-train-co/bullet_train-core.git'
gem "bullet_train-incoming_webhooks", git: 'http://github.com/bullet-train-co/bullet_train-core.git'
gem "bullet_train-themes", git: 'http://github.com/bullet-train-co/bullet_train-core.git'
gem "bullet_train-themes-light", git: 'http://github.com/bullet-train-co/bullet_train-core.git'
gem "bullet_train-integrations", git: 'http://github.com/bullet-train-co/bullet_train-core.git'
gem …
```
=> `bin/hack --link github`

bullet_train-super_scaffolding/lib/scaffolding/transformer.rb
Closes #198.
In the Transformer, we add a link for the first attribute here:
https://github.com/bullet-train-co/bullet_train-core/blob/b79f9d926615b7d34aabbf0259e45012a4e104af/bullet_train-super_scaffolding/lib/scaffolding/transformer.rb#L994-L996
However, we skip this logic if `cli_options[skip-table]` is `true`:
https://github.com/bullet-train-co/bullet_train-core/blob/b79f9d926615b7d34aabbf0259e45012a4e104af/bullet_train-super_scaffolding/lib/scaffolding/transformer.rb#L969
We set `cli_options[skip-table]` to `true` here, so `text_area` and other related attributes don't get scaffolded with a link:
https://github.com/bullet-train-co/bullet_train-core/blob/b79f9d926615b7d34aabbf0259e45012a4e104af/bullet_train-super_scaffolding/lib/scaffolding/transformer.rb#L785-L788
This means we get …
=> Ensure first Super Scaffolded attribute has link

bullet_train/app/models/concerns/invitations/base.rb
Closes #192.
I searched around for different attributes to change over, but there was a lot of logic that wasn't compatible with this method.
For instance, I tried to write the following in `bullet_train-outgoing_webhooks/app/models/concerns/webhooks/outgoing/delivery_attempt_support.rb`:
```ruby
attribute :attempt_number, default: -> { delivery.attempt_count + 1 }
before_create do
self.attempt_number = delivery.attempt_count + 1
end
```
However, at this point in the initialization process `delivery` was undefined, so I got an error.
I also tried just simply using a method defined in the same file. For example, I wrote the following in `bullet_train-outgoing_webhooks/app/models/concerns/webhooks/outgoing/event_support.rb`:
```ruby
attribute :payload, default: -> { generate_payload } …
```
=> Use `attribute` method in `Invitation` base

bullet_train-outgoing_webhooks/app/models/concerns/webhooks/outgoing/delivery_attempt_support.rb
closes https://github.com/bullet-train-co/bullet_train-core/issues/131
The reason urls without trailing slashes are not delivered is because `Net::HTTP` throws this error `ArgumentError: HTTP request path is empty` for those. When doing URI.parse the endpoint url without trailing slashes end up with an empty string in the `uri.path`. And those are technically considered invalid.
The fix is to add the trailing slash if one does not already exist to the `path` part of the `HTTP::URI`
Tested with pipedream that both urls with and without trailing slashes (as entered by the user in the webhooks UI) are delivered successfully. And no error in the logs.
=> Fix outgoing webhook delivery for url without trailing slash

bullet_train/lib/bullet_train/resolver.rb
Since we moved the gems to `bullet_train-core`, `bin/resolve` needed to be fixed in a couple of places.
=> Minor fixes to `bin/resolve`

bullet_train-themes-light/app/views/themes/light/layouts/_devise.html.erb
I think this was accidentally removed in #106 (https://github.com/bullet-train-co/bullet_train-core/pull/106/files#diff-1fc68ed0b53bacc67d976dbe546254e88c0e4016a29ec3396680ce86505ce4a4L2)
This makes the opening html tag match the opening tag in the `_account` layout.
Fixes #112
=> Add back the opening HTML tag on the devise layout

bullet_train-themes-light/app/views/themes/light/menu/_item.html.erb
This is a very minor detail, but the first link in the item menu was getting rounded even when the logo was present:
=> Adjust condition for making navbar link rounded

bullet_train-themes-light/app/assets/stylesheets/light/fields/trix_editor.css
Closes #150.
Tailwind's [preflight styles](https://tailwindcss.com/docs/preflight) were overriding the Trix Editor styles. Adam Wathan posted a workaround [here](https://github.com/tailwindlabs/tailwindcss/issues/989#issuecomment-506555308) which I used. I also added another style to make the toolbar icons clearer to see.
I wanted to change the `color` CSS property for the icons, but since they're all images we'd have to [change the background image](https://github.com/basecamp/trix/issues/464) for each icon, which I figured wasn't worth the effort.
For some reason Firefox displays a red ring around the trix editor when it's focused. The file in [this issue](https://github.com/tailwindlabs/tailwindcss/discussions/6749) has the same styles that were overriding our `ol` and `ul` tags here …
=> Fix Trix Editor styling

bullet_train/bullet_train.gemspec, bullet_train/docs/application-options.md, bullet_train/lib/bullet_train.rb
Closes #212.
Joint PR
- https://github.com/bullet-train-co/bullet_train/pull/709
Using an organization ID is optional, but I thought I'd add it here just in case.
=> Add OpenAI defaults to `bullet_train`

bullet_train-super_scaffolding/lib/scaffolding/transformer.rb
Fixes https://github.com/bullet-train-co/bullet_train/issues/724
Since `create_table` can take keyword arguments such as `options:` or `force:`, the regexp here should be able to pick up on those.
We could honestly get away with the following:
```ruby
`grep "create_table :#{class_names_transormer.table_name}" db/migrate/*`.split(":").first
```
I went ahead with the more specific regexp though.
=> Update migration search regexp to permit `create_table` options

.circleci/config.yml, Gemfile, Gemfile.lock, bullet_train-api/.circleci/config.yml, bullet_train-fields/.circleci/config.yml, bullet_train-outgoing_webhooks/.circleci/config.yml, bullet_train-roles/.circleci/config.yml, bullet_train-sortable/.circleci/config.yml, bullet_train-super_scaffolding/.circleci/config.yml, bullet_train-themes-light/.circleci/config.yml, bullet_train-themes-tailwind_css/.circleci/config.yml, bullet_train-themes/.circleci/config.yml, bullet_train/.circleci/config.yml
Continuation of https://github.com/bullet-train-co/bullet_train/pull/733
This PR ensures we use Ruby 3.2.2 and that 3.2.2 is used in our CI tests.
=> Update to Ruby 3.2.2 to match the starter repository

Gemfile.lock, bullet_train/Gemfile.lock, bullet_train/bullet_train.gemspec
Now that CableReady v5 has finally landed, it's time to integrate it.
This branch is intended for use with an older version of nice_partials (hence branched off at BT v1.2.11), but will be rebased once those issues are resolved. cc @andrewculver
=> Bump CableReady to v5.0

bullet_train/lib/bullet_train/resolver.rb
@kaspth
The regular expression was working when resolving files in public releases of gems like so:
```
bullet_train-1.2.26
```
However, when running a matching branch between the starting repository and `bullet_train-core` in CircleCI, this string was showing up in the resolver:
```
bullet_train-core-b00a02bd513c/bullet_train/lib/bullet_train/resolver.rb
```
I went ahead and updated the regular expression so it handles both situations.
=> Fix resolver issue for GitHub branches

bullet_train/app/models/concerns/teams/base.rb, bullet_train/docs/billing/usage.md
`TeamSupport` was renamed to `HasTrackers` in https://github.com/bullet-train-pro/bullet_train-billing-usage/commit/e4d3aedaae06d10d8700df747c0b2d79cfb2a3d8
Additionally, the guide recommends adding `Billing::HasTrackers` (the guide needs updating to `Billing::Usage::HasTrackers` too) directly.
So we aren't expecting this code to run and we can remove it.
=> Remove unused `Billing::Usage::TeamSupport` include

bullet_train/app/controllers/concerns/account/controllers/base.rb, bullet_train/app/models/concerns/memberships/base.rb, bullet_train/app/models/concerns/records/base.rb, bullet_train/app/models/concerns/teams/base.rb, bullet_train/lib/bullet_train/resolver.rb
This means collaborator gems, particularly the bullet_train-billing(-*) ones, can hook in and help define extra functionality. Here's how that would look:
```ruby
module BulletTrain::Billing::Teams::Base
extend ActiveSupport::Concern
included do
has_many :billing_subscriptions, class_name: "Billing::Subscription", dependent: :destroy, foreign_key: :team_id
end
end
ActiveSupport.on_load(:bullet_train_teams_base) { include BulletTrain::Billing::Teams::Base }
```
Collaborator gems must use concerns otherwise features won't be included into the class that includes `::Teams::Base`. That's because regular Ruby modules don't support this kind of deep nesting but concerns have specifically added that.
Note: this is also how Rails works internally and expects you to hook into its libraries, like …
=> Insert load hooks for collaborator gems

bullet_train-super_scaffolding/app/views/account/scaffolding/absolutely_abstract/creative_concepts/_index.html.erb, bullet_train-super_scaffolding/app/views/account/scaffolding/completely_concrete/tangible_things/_index.html.erb
Changes the way table rows in super scaffolded index views are rendered from a loop to a native `render partial: ... collection: ...` call.
This has multiple advantages:
1. It is highly optimized for Russian doll caching by adding `cached: true` (which will use multi-fetch if the cache store supports it)
2. It provides a `counter` local variable inside the rendered partial
=> Render table rows as collections

bullet_train/docs/billing/usage.md
I don't know how to test this, I don't have access to Bullet Train Pro, but there seems to be discrepancy between mentioned module name
and the actual module name included in the code snippet.
=> Docs: Usage: Include correct concern name; Fix typo

bullet_train-super_scaffolding/lib/scaffolding/script.rb
I tend to forget which data types should be used for our field partials, so I added a flag to list all the information via the terminal:
```
> bin/super-scaffold --field-partials
```
=> Show a list of the field partials with `bin/super-scaffold`

bullet_train/app/controllers/concerns/account/teams/controller_base.rb
Closes https://github.com/bullet-train-co/bullet_train/issues/692.
We have this `prepend_before_action` block in the teams controller base:
```ruby
prepend_before_action do
if params["action"] == "new"
current_user.current_team = nil
end
end
```
However, since this is happening early on in the request process, we were getting the error in the original issue because authorization hadn't actually been checked yet, and `current_user` was `nil`.
After adding the fix, when trying to access `account/teams/new` the app correctly redirects us and shows the following notification.
=> Ensure logged out user is redirected to sign in on `teams#new`

bullet_train-themes-light/app/assets/stylesheets/light/fields/trix_editor.css
Closes #214.
After a lot of trial and error, I eventually found SVGs that work and also that match the trix editor buttons.
The trix editor uses icons from Google's Material Design collection as per the [README](https://github.com/basecamp/trix/blob/main/assets/trix/images/README.md). There's a link to the collection in [this comment](https://github.com/basecamp/trix/issues/464#issuecomment-341529955), and although I found the icons, it was giving me the following svg code, and I couldn't get this to work at all (this is for the bold icon):
```HTML
<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#FFFFFF"><path d="M0 0h24v24H0z" fill="none"/><path d="M15.6 10.79c.97-.67 1.65-1.77 1.65-2.79 0-2.26-1.75-4-4-4H7v14h7.04c2.09 0 3.71-1.7 3.71-3.79 …
```
=> Override trix editor SVGs for dark mode

bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/attributes/_file.erb, bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/fields/_file_field.html.erb, bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/fields/_options.html.erb, bullet_train/config/locales/en/base.yml
Closes #204.
The only file field localization that isn't covered here is `Select Another File`:
https://github.com/bullet-train-co/bullet_train-core/blob/b2c0bd2762286a80bb4bd585df21c9ff56bf504d/bullet_train-fields/app/javascript/controllers/fields/file_field_controller.js#L88
We used [i18n-js](https://github.com/fnando/i18n-js) in the past a while back before the Tailwind repository, so if we  want to implement that again I'd be glad to work on it.
=> Add localizations for file fields

bullet_train/lib/bullet_train.rb
Closes #244.
It seems like we want this to be dependent on the presence of the gem itself as opposed to the environment variable, but I included this check just in case since subscriptions won't work if the API key isn't there.
Also, since the `bullet_train-billing` and `bullet_train-billing-stripe` gems are each their own thing, I can look into this deeper if we want to separate the logic and only check for the Stripe API key when using `bullet_train-billing-stripe`.
cc/ @jagthedrummer
=> Add environment variable check for `billing_enabled?` helper

bullet_train-themes-light/app/views/themes/light/fields/_field.html.erb, bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/fields/_field.html.erb
More of the work spun off from #159.
We're updating both the light and tailwind_css `fields/_field` partial to grab the old `content_for` keys and copy them to Nice Partials' `partial.x` syntax, then we're clearing the old data `flush_content_for` with.
This lets us use Nice Partials' syntax internally while still having backwardscompatibility with any other themes.
We could also consider adding a deprecation warning when people use `content_for` with our field partial, but I'll look at that after I've updated our `fields/_field` using partials to not use `content_for`.
=> Remove flush_content_for in themes _field partial

bullet_train/app/models/billing/mock_limiter.rb
This was causing failures in some of the billing repos. This PR just makes the call signatures match.
https://github.com/bullet-train-pro/bullet_train-billing-usage/blob/82f5f77242125dc1da05b57fef2efa6b7e4db9d3/app/models/concerns/billing/limiter/base.rb#L26-L30
=> Update the mock lmiter to match the call signature of the real limiter

bullet_train-themes-light/app/assets/stylesheets/light/application.css
The following is when the theme is set to `:emerald`
https://user-images.githubusercontent.com/10546292/229503040-f11c472a-5e1a-41a8-b0b5-fc72add37af9.mov
The archived repository [TurboLinks](https://github.com/turbolinks/turbolinks#advanced-usage) had instructions on how to change this:
```css
.turbolinks-progress-bar {
height: 5px;
background-color: green;
}
```
So I had to fish for the proper class in the new turbo-rails repository, which turned out to be `.turbo-progress-bar` ([source](https://github.com/hotwired/turbo-rails/blob/7402db85029092ec49dca4a020a7de51b6fa5e8b/app/assets/javascripts/turbo.js#L1458))
=> Use the application's default color for the Turbo progress bar

bullet_train-super_scaffolding/lib/scaffolding/transformer.rb
We were skipping the sortable controller when Super Scaffolding text attributes like `trix_editor`. However, now that we have #199 in place, it should be safe to allow the sortable option in this situation.
=> Add sortable controller for models with text attributes

bullet_train-api/app/helpers/api/open_api_helper.rb, bullet_train-api/lib/bullet_train/api/example_bot.rb
Since we weren't passing the model as a symbol to `FactoryBot.get_example` in the OpenApi helper, we were getting strings and not symbols.
For example, the webhooks outgoing endpoint model had the following backtrace:
```
"/Users/gabriel_zayas/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/transactions.rb:209:in `transaction'",
"/Users/gabriel_zayas/work/bt/bullet_train/local/bullet_train-core/bullet_train-api/lib/bullet_train/api/example_bot.rb:12:in `example'",
"/Users/gabriel_zayas/work/bt/bullet_train/local/bullet_train-core/bullet_train-api/lib/bullet_train/api/example_bot.rb:122:in `_set_values'",
"/Users/gabriel_zayas/work/bt/bullet_train/local/bullet_train-core/bullet_train-api/lib/bullet_train/api/example_bot.rb:90:in `_path_examples'", …
```
=> Pass symbol instead of string to `Factorybot.get_example`

bullet_train-super_scaffolding/lib/bullet_train/super_scaffolding/scaffolders/oauth_provider_scaffolder.rb
Closes https://github.com/bullet-train-co/bullet_train-core/issues/248.
Applies the `oauth_transform_string` function to the foreign key definition being added to the incoming webhooks migration of a newly created OAuth provider.
=> Transform incoming webhooks foreign key index name when super scaffolding a new OAuth provider

bullet_train-themes-light/app/views/showcase/previews/tailwind/utilities/_spacing.html.erb
Addresses the TODO in `bullet_train-themes-light/app/views/showcase/previews/tailwind/utilities/_spacing.html.erb`
The result isn't that different from the styles for `space-x` and `space-y` which were already there. However, I had trouble getting some of the spacing to work with `flex`.
From the [Tailwind docs](bullet_train-themes-light/app/views/showcase/previews/tailwind/utilities/_spacing.html.erb):
> Use gap-{size} to change the gap between both rows and columns in grid and flexbox layouts.
I went ahead and updated `Vertical Gaps` with `grid` for this reason.
=> Add gap-y and gap-x to showcase partial

bullet_train-api/app/controllers/concerns/api/v1/users/controller_base.rb
When updating a user with a cloudinary photo for their profile, the user was being "successfully updated," but we didn't have this strong parameter so the image wasn't actually being saved to the User.
This fix ensures the image is saved and can be seen in the circle in the menu bar in place of the `ui-avatars` avatar.
=> Permit cloudinary photo in User strong parameters

bullet_train/app/helpers/invitation_only_helper.rb
closes https://github.com/bullet-train-co/bullet_train-core/issues/288
**Overview**
Updated the comparison for `invitation_keys` to use `secure_compare`
**Testing Done**
Set values in `ENV['INVITATION_KEYS']` locally and navigate to the `/invitation?key=XYZ`. Ensure that for keys that match one of the ones set in the environment variable, we are redirected correctly to create a new user or a new team. For keys that do not match, we are redirected to 404.
=> use secure_compare for invitation keys

bullet_train-api/app/views/account/platform/access_tokens/new.html.erb
Closes #296.
Nice Partials states the following for using the `t` method:
https://github.com/bullet-train-co/nice_partials/blob/63f28a70eca0808a2474ca2a9cc8549acc799fca/lib/nice_partials/partial.rb#L23-L38
You can see that an invocation like `partial.t :description, title: "some.custom.key"` needs just the key, not the translated value, so I fixed that here.
=> Pass parameters properly to new access token nice partial translation

bullet_train-themes-light/app/views/themes/light/menu/_subsection.html.erb
Closes #278.
Replaces `.underscore` with `.parameterize(separator: '_')` in producing DOM ids from a title.
Using `parameterize` instead of `gsub` or `tr` not only downcases the string and replaces spaces with underscores, but also handles other special characters by converting them into their ASCII equivalents, which is useful for creating URL-friendly strings.
=> Fix: Produce really underscored DOM ids from a title

bullet_train/app/views/devise/registrations/new.html.erb
The password and confirmation fields & labels overlap on narrow screens.
=> Stack registration password and confirmation on mobile

bullet_train-themes-light/app/assets/stylesheets/light/application.css, bullet_train-themes-light/app/views/themes/light/menu/_item.html.erb
Handling the TODO way back from this PR:
- https://github.com/bullet-train-co/bullet-train-tailwind-css/pull/315
This time around presented a challenge because now that we have flyout subsections, the hover groups weren't working properly. I added a name to the nested group for it to work. I found a pretty cool entry in the [Tailwind docs](https://tailwindcss.com/docs/hover-focus-and-other-states#differentiating-nested-groups) that led me to solve the issue:
> When nesting groups, you can style something based on the state of a specific parent group by giving that parent a unique group name using a `group/{name}` class, and including that name in modifiers using classes like `group-hover/{name}`
I also changed `px-2` to `px-3` because when the navigation bar is set to `:top` and when …
=> Use Tailwind for navigation bar link animation

bullet_train-themes-light/app/views/themes/light/attributes/_block.html.erb, bullet_train-themes-light/app/views/themes/light/attributes/_progress_bar.html.erb, bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/attributes/_code.html.erb, bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/attributes/_file.erb, bullet_train-themes/app/views/themes/base/attributes/_belongs_to.html.erb, bullet_train-themes/app/views/themes/base/attributes/_block.html.erb, bullet_train-themes/app/views/themes/base/attributes/_boolean.html.erb, bullet_train-themes/app/views/themes/base/attributes/_code.html.erb, bullet_train-themes/app/views/themes/base/attributes/_date.html.erb, bullet_train-themes/app/views/themes/base/attributes/_date_and_time.html.erb, bullet_train-themes/app/views/themes/base/attributes/_days_ago.html.erb, bullet_train-themes/app/views/themes/base/attributes/_email.html.erb, bullet_train-themes/app/views/themes/base/attributes/_has_many.html.erb, bullet_train-themes/app/views/themes/base/attributes/_html.html.erb, bullet_train-themes/app/views/themes/base/attributes/_image.html.erb, bullet_train-themes/app/views/themes/base/attributes/_number.html.erb, bullet_train-themes/app/views/themes/base/attributes/_option.html.erb, bullet_train-themes/app/views/themes/base/attributes/_options.html.erb, bullet_train-themes/app/views/themes/base/attributes/_phone_number.html.erb, bullet_train-themes/app/views/themes/base/attributes/_text.html.erb
Closes #115 
Instead of `object.send(attribute).present?` it would probably be better to use `object.respond_to?(attribute)`. For other cases `public_send` should work fine.
=> Prefer `.public_send` over `.send` in partials

bullet_train-themes/app/views/themes/base/fields/_password_field.html.erb
I was looking into this TODO:
```
<% # TODO This is the wrong place to define this kind of style, but I couldn't make this work in the `:help` content buffer. %>
```
I found out that the text wasn't actually showing up as red, so I fixed that here.
I'd like to work on the TODO itself, just not entirely sure right now if we need to move the entire `div` itself or just the style, and I'm still not entirely sure how `content_for :help` is being rendered here if that's what we're using so I'll have to figure that out too.
=> Fix red text for password strength indicator

bullet_train-themes-light/lib/bullet_train/themes/light.rb
We can remove this since the following have been merged:
- https://github.com/bullet-train-co/bullet_train/pull/575
- https://github.com/bullet-train-co/bullet_train-core/pull/33
=> Remove unneeded attribute `original_devise_path`

bullet_train-themes-light/app/views/showcase/engine/_head.html.erb
Let's the configured theme colors be used in Showcase automatically.
What we want before https://github.com/bullet-train-co/bullet_train-core/pull/377
Closes https://github.com/bullet-train-co/showcase/issues/68
=> Inject Light theme colors into Showcase

bullet_train-themes/lib/bullet_train/themes.rb
```ruby
INVOCATION_PATTERNS = [
/^account\/shared\//,
/^shared\//,
]
```
Since this feels more like Bullet Train internal information, I feel like we don't have a need to make this configurable.
We also have this entry in the [docs](https://bullettrain.co/docs/themes) which shows developers that they should be using the same invocation even if they're using a different theme:
=> Delete unneeded TODO in `themes.rb`

bullet_train-themes-light/app/views/showcase/previews/partials/_breadcrumb.html.erb
Addresses the TODO in `bullet_train-themes-light/app/views/showcase/previews/partials/_breadcrumb.html.erb`.
I found that this is an easy URL that we can use in all Bullet Train applications.
https://github.com/bullet-train-co/bullet_train-core/blob/350023aa4c3116f4df89c85f6dd2d7dbf8261bbf/bullet_train/app/views/account/invitations/_breadcrumbs.html.erb#L4
I wrote `current_team` here, but we can change that if necessary.
=> Add showcase example for breadcrumb with model `url_for`

bullet_train-super_scaffolding/lib/scaffolding/transformer.rb
I think this comment was helpful when initially moved everything to `bullet_train-core`, but not that we've been here for a while I feel like we don't need this comment anymore.
=> Remove unnecessary comment

bullet_train-themes-light/app/views/themes/light/_alert.html.erb
I'm just starting out with Bullet Train. I noticed that alert message was not very readable due to color contrast between text and background was too low:
<details><summary>Before this change</summary>
https://webaim.org/resources/contrastchecker/?fcolor=B91C1C&bcolor=FCA5A5
</details>
<details><summary>After this change</summary>
https://webaim.org/resources/contrastchecker/?fcolor=7F1D1D&bcolor=FEE2E2
</details>
<details><summary>For comparison, here's Bootstrap's alert</summary>
https://getbootstrap.com/docs/5.3/components/alerts/
https://webaim.org/resources/contrastchecker/?fcolor=58151C&bcolor=F8D7DA
</details>
<details><summary>Tailwind CSS alert</summary>
https://tailwindui.com/components/application-ui/feedback/alerts#component-bfa7bc8484740ff2b3dfabe5fd318b25 …
=> Fix color contrast issues for flash error/red alert

bullet_train/docs/index.md
- Renames "Production" to "Deployment" matching the sidebar.
- Add a Showcase link like https://github.com/bullet-train-co/bullet_train-core/pull/375 did for the sidebar. — Rename UI to User Interface.
- Rename other links to be a direct mirror of their sidebar version, except in cases like Dealing with Indirection where the TOC version explains more.
- Explicitly name "Magic Test" in TOC, so it's easier to connote with the sidebar version.
=> Make Table-of-Contents a closer match to the Sidebar

bullet_train/app/helpers/attributes_helper.rb
Seems like we can just use one hash to store the settings in. And then use keyword argument defaults to preserve the old behavior of keeping the previous setting in case no override is passed.
This also uses `rescue` so we revert to the previous values in case an exception is thrown.
=> Refactor `with_attribute_settings`

bin/checkout-and-link-starter-repo
This should make it easier(/possible) to test joint PRs across the `core` repo and the starter repo.
=> Better branch matching against the starter repo

bullet_train-super_scaffolding/lib/scaffolding/transformer.rb
When transforming strings, I felt that it would be easier to keep track of everything if we just singularlized the strings instead of keeping two separate lists.
=> Minor refactoring in Transformer

bullet_train-api/config/routes.rb
Since we already have this if statement in the controller itself, we should be able to simply declare this route and only have the environment variable check once:
```ruby
def provision
if ENV["TESTING_PROVISION_KEY"].present? && params[:key] == ENV["TESTING_PROVISION_KEY"]
...
end
end
```
The tests in https://github.com/bullet-train-co/bullet_train/pull/533 will also pass for both situations when `ENV["TESTING_PROVISION_KEY"]` is present and when it is not.
=> Remove environment variable check for `/testing/provision` route

bin/checkout-and-link-starter-repo, bullet_train/app/models/concerns/teams/base.rb
Addresses the TODO in `bullet_train/app/models/concerns/teams/base.rb`.
Since we're ultimately looking for `User` ids, I thought it would be quicker/clearer to make a query directly to the `User` model. `User` has an attribute called `platform_agent_of_id`, so with this we can tell if the `User` is a dummy for the Application or an actual person:
```ruby
users.where.not(platform_agent_of_id: nil)
```
Since we have access to the `users` variable, we can be sure the users are scoped to the Team making the query.
With the previous code:
```
Team Load (0.6ms)  SELECT "teams".* FROM "teams" ORDER BY "teams"."id" ASC LIMIT $1  [["LIMIT", 1]]
Membership Load (0.4ms)  SELECT "memberships".* FROM "memberships" WHERE "memberships"."team_id" = $1 AND "memberships"."platform_agent_of_id" IS NOT NULL …
```
=> Refactor `platform_agent_access_tokens` db query

bullet_train/docs/field-partials/file-field.md
I'm assuming this refers to generating a migration which file attachments don't require, but I don't think we actually need this because you can scaffold a crud-field document with the other steps written here, and there's no command/code written after this particular sentence, so I decided to delete it.
=> Remove unneeded lines from docs

bullet_train-fields/app/javascript/controllers/fields/super_select_controller.js, bullet_train-themes/app/views/themes/base/fields/_super_select.html.erb, bullet_train/docs/field-partials/super-select.md
Closes https://github.com/bullet-train-co/bullet_train/issues/783
Joint PR
- https://github.com/bullet-train-co/bullet_train/pull/799
Since we have no way of editing Super Select options from the starter repository, I added this target to the Super Select stimulus controller so we can customize these elements to our liking without having to eject any files.
Linking up to the JS code in bullet_train-core can be super flaky so I'm trying my best to test everything well. I'll have to double check my work on this one (especially with the spread operator to merge the two objects).
Also just curious if this presents any security issues since we're technically passing in raw JavaScript from the DOM.
Anyways, I worked through a number of ideas in the [original …
=> Add super select config target to get options from main app

.circleci/config.yml
Previously we could introduce changes in `core` that would break tests in the starter repo, but that wouldn't show up as failures in `core`.
This was due to the fact that we were running more tests in the starter repo than we were runnig here.
This PR makes it so that we run the extra tests so that we can spot test failures here.
Fixes #391
=> We should run the super_scaffolding_partial_test as well

bullet_train-themes-light/lib/tasks/application.rb
This was a tough one. A lot changed with `bullet_train-core`, so I had to specify the three `themes` gems we use, and since we're pulling files from different places, I tried my best to make it as dynamic as possible.
I'll still have to look into the `publish` task as well, but we're not getting the `tailwind.mailer.light.config.js` file ejected when running the eject command for some reason (See #26). The file exists in `bullet_train-core`, but it's not in the gem when downloaded from rubygems.org.
Besides that this one should be good to go, but if there's anything that seems off, I'd be glad to look over the code again.
=> Fix clean theme rake task

bullet_train/docs/super-scaffolding.md, bullet_train/docs/super-scaffolding/options.md
Closes #151.
As far as the `--skip-*` flags, I'm not sure how many of these we actually want to document.
For example, I'm under the impression that `--skip-table` is only for use internally (check out #199) so I didn't document it here. Maybe some of these can be set within the scope of the Transformer and removed from `cli_options`.
Besides that, I didn't document `--skip-parent` because I don't think we have the logic for it implemented as of now.
I also added `--navbar` instead of `--sidebar` if #209 gets merged.
=> Documentation: Super Scaffolding Options

bin/checkout-and-link-starter-repo
This makes it so that we're running tests against the JS provided by `core` instead of against the published versions of the packages on npm.
=> Link npm packages in CI

bullet_train/Gemfile, bullet_train/app/helpers/account/markdown_helper.rb, bullet_train/bullet_train.gemspec
As discussed in #384 within https://github.com/bullet-train-co/bullet_train-core/pull/384#issuecomment-1668523752
Bullet Train apps can still do `bundle update --pre commonmarker` to get the new version going but we don't force it on them now.
=> Contain commonmarker upgrade to just Bullet Train for now

.circleci/config.yml
We need to do this so that the `core` js packages get included correctly.
=> Run `yarn build` in CI

bullet_train-themes-light/app/views/showcase/engine/_head.html.erb
https://github.com/bullet-train-co/bullet_train-core/pull/378 accidentally removed the application JavaScript and CSS from being bundled in Showcase.
This adds them back.
=> Add back linking the application assets in Showcase

bullet_train-themes/app/views/themes/base/fields/_emoji_field.html.erb
As noted in https://github.com/bullet-train-co/bullet_train-core/pull/188#issuecomment-1675992829
Fixes the deprecation warning of using the old `data-target` syntax:
> [Warning] Please replace data-target="fields--emoji-picker.display" with data-fields--emoji-picker-target="display". The data-target attribute is deprecated and will be removed in a future version of Stimulus. –
> <span data-target="fields--emoji-picker.display">😘</span>
For some reason it didn't fire on the `data-target="<>.button"`, but that is fixed too.
We were already using the new syntax for the `input` target, so there shouldn't be any concerns over switching to this.
=> Fix Stimulus targeting in emoji picker

bin/release-all
We should use `bump current` to get the current version number instead of using `bump patch` which increments it.
=> Release workflow bug fix

.github/workflows/version-bump.yml
This will make it so that we can tell who initiated a version bump, which seems reasonable since it's a manual action, and not automated.
=> [release process] Add committer to the version bump PRs.

.github/workflows/publish-release.yml
This adds a workflow that will add a GitHub release after a version tag has been pushed to the repo.
The version tag is automatically pushed when we merge a PR that's been generated by the "Create Version Bump PR For Ruby Gems & NPM Packages" workflow.
=> [release process] Auto publish releases

bullet_train-super_scaffolding/app/models/scaffolding/absolutely_abstract/creative_concept.rb
#408
I'm not entirely sure why the records are being returned in descending order, and my tests are failing locally but CI seems to be passing. Accessing TangibleThings via their CreativeConcept will return them in descending order:
<details>
<summary>In the CreativeConcept show action:</summary>
```
From: /Users/gabriel_zayas/work/bt/bullet_train/local/bullet_train-core/bullet_train-super_scaffolding/app/controllers/account/scaffolding/absolutely_abstract/creative_concepts_controller.rb:17 Account::Scaffolding::AbsolutelyAbstract::CreativeConceptsController#show:
16: def show
=> 17:   binding.pry
18: end
[1] pry(#<Account::Scaffolding::AbsolutelyAbstract::CreativeConceptsController>)> Scaffolding::CompletelyConcrete::TangibleThing.where(absolutely_abstract_creative_concept_id: …
```
=> Add temporary fix for `TangibleThing` order

.github/workflows/publish-release.yml
Apparently tags created via the API in a GitHub action don't count as being "pushed". Trying a different approach.
=> [release process] Try another way of auto-running

.github/workflows/tag-release.yml
I'm having trouble getting a dedicated action for creating a relase to work, so maybe we can do it immediately after tagging.
=> [release process] Try tag & release in the same action

.github/workflows/tag-release.yml
This should (finally) make it so that we automatically publish a GitHub relase when we tag a version.
=> [release process] Pass the tag name to the release action

.github/workflows/tag-release.yml
We don't need to pass a value to a workflow that doesn't need it.
=> [release process] One more fix

CHANGELOG.md, bin/bump-all
Instead of trying to maintain the CHANGELOG manually, let's just point people to the GitHub releases area that is automatially tracking all of this stuff.
=> [release process] Use auto generated CHANGELOG

bullet_train-super_scaffolding/lib/scaffolding/transformer.rb
Joint PR
- https://github.com/bullet-train-co/bullet_train/pull/706
In our system tests, we pass the sidebar flag like this:
```
--sidebar="ti.ti-world"
```
This doesn't correctly scaffold the icon though, so I fixed it here.
I wanted to originally write this, but the script didn't play well with spaces:
```
--sidebar="ti ti-world"
```
Now we can just pass it like this:
```
--navbar="ti-world"
```
I also just changed this to `navbar` since the developer can choose to have a sidebar or a navbar at the top.
=> Fix scaffolding with sidebar flag

bullet_train-api/lib/bullet_train/api/example_bot.rb
reset_pk_sequence is only available for Postgres, not MySQL, so check that the method is available before calling.
=> Fix for `api/example_bot` to work on non-postgres apps

bullet_train-api/app/helpers/api/open_api_helper.rb, bullet_train-api/app/views/api/v1/open_api/shared/_paths.yaml.erb, bullet_train-api/lib/bullet_train/api/example_bot.rb
Fixes generation of path methods (`get_examples`, `post_parameters` etc.)
Requires https://github.com/bullet-train-co/bullet_train/pull/738
=> Fix: Paths methods generation for OpenAPI

bullet_train/app/controllers/concerns/documentation_support.rb
I looked into the TODO in the `DocumentationSupport` module, and although this doesn't fix it, it gives us a speed boost by caching the `bundle show bullet_train` output.
I can't think of another way right now to access the docs from the gem in the context of a Bullet Train app besides linking to each raw file here on GitHub, but I feel like that would be slower anyways. I'm personally okay with `bundle show bullet_train` initially if we keep this cache, but I didn't delete the TODO just in case there's another way we want to approach this problem.
=> Cache the base path of `bullet_train` when accessing documentation

bullet_train-api/test/dummy/config/locales/en.yml, bullet_train-fields/test/dummy/config/locales/en.yml, bullet_train-has_uuid/test/dummy/config/locales/en.yml, bullet_train-incoming_webhooks/test/dummy/config/locales/en.yml, bullet_train-integrations-stripe/test/dummy/config/locales/en.yml, bullet_train-integrations/test/dummy/config/locales/en.yml, bullet_train-obfuscates_id/test/dummy/config/locales/en.yml, bullet_train-outgoing_webhooks/test/dummy/config/locales/en.yml, bullet_train-roles/test/dummy/config/locales/en.yml, bullet_train-scope_questions/test/dummy/config/locales/en.yml, bullet_train-sortable/test/dummy/config/locales/en.yml, bullet_train-super_load_and_authorize_resource/test/dummy/config/locales/en.yml, bullet_train-super_scaffolding/test/dummy/config/locales/en.yml, bullet_train-themes-light/test/dummy/config/locales/en.yml, bullet_train-themes-tailwind_css/test/dummy/config/locales/en.yml, bullet_train-themes/test/dummy/config/locales/en.yml, bullet_train/app/controllers/concerns/controllers/base.rb, bullet_train/config/locales/en/base.yml, bullet_train/test/dummy/config/locales/en.yml
See https://guides.rubyonrails.org/i18n.html#managing-the-locale-across-requests
Setting the locale using I18n.locale = 'es' during the request/response lifecycle can leak to other request/responses in the same thread.
Using I18n.with_locale instead limit the locale change to the underlying block and does not leak the value of I18n.locale to other requests. It is also the recommended way to handle locale change as per the rails doc.
=> Fix request safety issue in set_locale

bullet_train-api/app/helpers/api/open_api_helper.rb
Sends FactoryBot examples to JbuilderSchema for proper attributes and properties examples in schemas.
This fixes empty examples in 
```yaml
components:
schemas:
XXXAttributes:
XXXParameters:
```
=> Fix: Empty examples in schemas in OpenAPI

Gemfile.lock, bullet_train-api/app/helpers/api/open_api_helper.rb, bullet_train-api/app/views/api/v1/open_api/shared/_paths.yaml.erb, bullet_train-api/bullet_train-api.gemspec, bullet_train-api/lib/bullet_train/api.rb, bullet_train-api/lib/bullet_train/api/example_bot.rb, bullet_train-api/lib/jbuilder/hacks.rb, bullet_train-api/lib/jbuilder/values_transformer.rb
Closes https://github.com/bullet-train-co/bullet_train/issues/734
Requires https://github.com/bullet-train-co/bullet_train/pull/749
- Fixes warnings shown by `yarn exec redocly lint http://127.0.0.1:3000/api/v1/openapi.yaml`
- Includes https://github.com/bullet-train-co/bullet_train-core/pull/236 and https://github.com/bullet-train-co/bullet_train-core/pull/258
- Test `test/controllers/api/open_api_controller_test.rb` in starter repo was rewritten to fail on warnings
- Upgraded `jbuilder-schema` to `>= 2.2.0`
- Added Jbuilder hack module in `bullet_train-api/lib/jbuilder/values_transformer.rb` to modify attributes produced by external classes, by now it replaces `ActionText::RichText` object with it's `body` value. More can be added if needed.
=> Fix: OpenAPI warnings

bullet_train-themes-light/app/assets/stylesheets/light/application.css, bullet_train-themes-light/app/assets/stylesheets/light/docs.css, bullet_train/app/helpers/account/markdown_helper.rb, bullet_train/app/views/layouts/docs.html.erb
Fixes #191
This relies on the `1.x` branch of the `commonmarker` gem, which is currently in pre-relase stages.
We're waiting for `1.x` to get to a general release before we update our dependencies and force the change on downstream users. The maintainer of that gem has estimated that the general release should happen sometime this fall, maybe around October. Once that release is available and once we've updated our depencency list this change should Just Work.
In the meantime downstream applications can opt-in to using a pre-release candidate of `commonmarker` by adding this to the `Gemfile`:
```ruby
gem 'commonmarker', '~> 1.0.0.pre10'
```
=> Generate clickable anchor links in `/docs`

bullet_train-api/app/controllers/concerns/api/controllers/base.rb, bullet_train-api/app/controllers/concerns/api/v1/invitations/controller_base.rb, bullet_train-api/app/views/api/v1/invitations/index.json.jbuilder, bullet_train-api/app/views/api/v1/invitations/show.json.jbuilder, bullet_train-api/config/routes.rb, bullet_train/app/controllers/concerns/account/invitations/controller_base.rb, bullet_train/app/models/concerns/invitations/base.rb, bullet_train/config/locales/en/invitations.en.yml
Implements memberships API and adds OpenAPI specs for invitations.
Requires https://github.com/bullet-train-co/bullet_train/pull/737
Replaced `has_many :roles, through: :membership` in `bullet_train/app/models/concerns/invitations/base.rb` with a method as `roles` is not a table.
=> Invitations API

bullet_train-incoming_webhooks/lib/bullet_train/incoming_webhooks/scaffolders/incoming_webhooks_scaffolder.rb, bullet_train/docs/tunneling.md
Fixes #474.
Also mentioned [here](https://github.com/bullet-train-co/bullet_train-core/issues/453#issuecomment-1687445312) which has more details about the fix.
=> Fix URL output for ngrok tunnel when super scaffolding an incoming webhook

bullet_train/lib/tasks/bullet_train_tasks.rake
Fixes #481.
As a side note, we should probably have tests for this task.
=> Ensure `bin/hack --reset` resets gems set to custom path

bullet_train-themes-light/bullet_train-themes-light.gemspec
Fixes https://github.com/bullet-train-co/bullet_train-core/issues/26
Since we weren't including this file in the package it was causing problems for people who were running with the released gems.
But the file would be available if you'd linked your core repos into the starter repo.
=> Add `tailwind.mailer.light.config.js` to the gem package

bullet_train-themes/app/views/themes/base/fields/_super_select.html.erb
Fixes https://github.com/bullet-train-co/bullet_train-core/issues/458
=> `super_select`'s `accepts_new` option automatically enables `search: true`.

bullet_train-outgoing_webhooks/app/views/api/v1/webhooks/outgoing/events/_event.json.jbuilder
Use parent_association setting for API output rather than hardcoded team in outgoing webhook events
=> Use parent_association setting for outgoing webhook events

.circleci/config.yml
Circle wasn't even getting to running the tests because it was failing with this error:
```
Installed version of Google Chrome is 116.0.5845.140 
116.0.5845.140 will be installed
curl: (22) The requested URL returned error: 404 
Exited with code exit status 22
```
This was due to Google releasing a new version of Chrome without releasing a corresponding version of chromedriver.
Some other issues for reference:
https://github.com/CircleCI-Public/browser-tools-orb/issues/90
https://github.com/CircleCI-Public/browser-tools-orb/issues/75
=> Get CircleCI running again

bullet_train-themes-light/app/views/showcase/engine/_head.html.erb
Adding `fixed` to the theme selector make it stick to the bottom of the browser window instead of being stuck all the way at the bottom of the scroll.
But if we _just_ add the `fixed` class, then the theme selector will overlap the content at the very bottom of the page and we have no way to get to it.
We can fix that by using a little bit of JS to calculate the height of the theme selector and then set that amount of padding on the bottom of the `main` container.
Doing that makes it so that there is a scrollbar if the theme selector will overlap any content at the bottom of the `main` container.
And makes it so that you can scroll all the way down and see all of the content.
=> Make the showcase theme selector sticky

bullet_train-super_scaffolding/lib/scaffolding/attribute.rb, bullet_train-super_scaffolding/lib/scaffolding/transformer.rb
Closes #476.
Most of the fixes are are straightforward, but the most important one to focus on here is the definition of `title_case`. It was introduced in https://github.com/bullet-train-co/bullet-train-tailwind-css/commit/a1c2eb1ab2c7b70fdbea680c731899cc54a39f63, updated in https://github.com/bullet-train-co/bullet-train-tailwind-css/commit/36788a3f3860a7e243385cdee72cf34c4867cada, and looked like the following before #124 was introduced:
```ruby
title_case = if is_ids
name_without_ids.humanize.titlecase
elsif is_id
name_without_id.humanize.titlecase
else
name.humanize.titlecase
end
```
In #476, the locale is expected to return `title_case` as `Circle Ci ID`. However, even if we write `name.humanize.titlecase` instead of `name_without_id.humanize.titlecase` above, `ID` is removed by …
=> Super Scaffold `vanilla` ID attributes properly

bullet_train/config/locales/en/framework_packages.yml, bullet_train/lib/tasks/bullet_train_tasks.rake
Closes #506
The addition to `framework_packages.yml` also ensures that `bullet_train-roles` is added to the Gemfile.
=> Point BT gems not originally in Gemfile to custom path with `bin/hack --link`, add roles gem

bullet_train-super_scaffolding/.circleci/config.yml, bullet_train/app/views/account/teams/_breadcrumbs.html.erb
This partial is included in all generated _breadcrumb partials, so all edit pages are always showing 'team settings', not just the team pages.
This fixes, so it's only shown when editing 'team', not any other model.
=> Fix breadcrumbs for edit pages

bullet_train-themes-light/app/views/themes/light/fields/_field.html.erb, bullet_train/app/views/account/onboarding/user_details/edit.html.erb, bullet_train/app/views/devise/registrations/new.html.erb, bullet_train/docs/field-partials.md
Fixes https://github.com/bullet-train-co/bullet_train-core/issues/379
Supersedes #499, based on [refinements suggested by @pascallaliberte](https://github.com/bullet-train-co/bullet_train-core/pull/499#issuecomment-1701010343)
Currently we show the red asterisk on required fields **only** if the object represented by the form has a validation for `presence` on that field. For instance on the user registration form we don't show an asterisk for `password_confirmation` because Devise doesn't setup a `validates_presence` validation for that field.
But the field really is required. If you fill in a password, but no confirmation and then submit the form, it causes an error.
If a developer were to eject the devise form they could add `options: { required: true}` to the form:
```diff
<%= render …
```
=> Introduce `other_options[:required]` for field partials

bullet_train-super_scaffolding/lib/bullet_train/super_scaffolding.rb, bullet_train-super_scaffolding/lib/bullet_train/super_scaffolding/scaffolders/crud_scaffolder.rb
Closes #475.
```
> rails g model Project title:string
invoke  active_record
create    db/migrate/20230831123427_create_projects.rb
create    app/models/project.rb
invoke    test_unit
create      test/models/project_test.rb
invoke      factory_bot
create        test/factories/projects.rb
> bin/super-scaffold crud Project Team title:text_field
rake aborted!
Project does not have a foreign key referencing Team.
Make sure you generate your model with a references type:
rails generate model Project team:references ...
/home/gazayas/work/bt/bullet_train/local/bullet_train-core/bullet_train-super_scaffolding/lib/bullet_train/super_scaffolding/scaffolders/crud_scaffolder.rb:46:in `run'
/home/gazayas/work/bt/bullet_train/local/bullet_train-core/bullet_train-super_scaffolding/lib/scaffolding/script. …
```
=> Check if model has foreign key to parent before Super Scaffolding

bullet_train-super_scaffolding/lib/scaffolding/transformer.rb
In the Themes localization PR (#393 ) I removed the scaffolding of assign_date and assign_date_and_time.
In order to remove a monkey patch of the super-scaffolding method from our codebase I need to remove it as well from this branch.
=> remove assign_date and assign_date_and_time scaffolding

.circleci/config.yml
With parallelism set to 16 we spend about 75-80% of the time in any given job doing setup, and only 20-25% of the time running tests. Decreasing parallelism will give us a better ratio, and shouldn't increase testing time all that much.
=> Decrease parallelism in CircleCI

bullet_train-incoming_webhooks/config/routes.rb, bullet_train-incoming_webhooks/lib/scaffolding/incoming_webhooks_transformer.rb, bullet_train-incoming_webhooks/test/controllers/webhooks/incoming/bullet_train_webhooks_controller_test.rb
Closes https://github.com/bullet-train-co/bullet_train-core/issues/453
Joint PR
- https://github.com/bullet-train-co/bullet_train/pull/947
I was stuck on this one for a while for a couple of reasons:
1. I originally tried to write system tests but decided it would be more beneficial to write controller tests. Also, getting the webhook parameters right for this one took some fine-tuning.
2. Since we usually use `Scaffolding::CompletelyConcrete::TangibleThing` and such to transform strings, I initially set out to scaffold using those kinds of strings. It wasn't until I was working in the `bullet_train-incoming_webhooks` transformer itself that it dawned on me that we were already doing this with `Webhooks::Incoming::BulletTrainWebhook` :man_facepalming:
```
bin/super-scaffold …
```
=> Super Scaffold incoming webhooks test

bullet_train-themes-light/lib/tasks/application.rb
When ejecting a new theme, we run this code on [bullet_train-themes-light/lib/bullet_train/themes/light.rb](https://github.com/bullet-train-co/bullet_train-core/blob/main/bullet_train-themes-light/lib/bullet_train/themes/light.rb) in the eject task:
https://github.com/bullet-train-co/bullet_train-core/blob/3b9366861f767fad751372c5e46a01becc8e7835/bullet_train-themes-light/lib/tasks/application.rb#L72-L75
This was removing `mattr_accessor :colors` which we want to stay, so it was causing a syntax error when trying to access the application after ejecting a custom theme:
```
rake bullet_train:themes:light:eject[foo]
```
I used Masamune again, especially because we introduced it in the same file in #312, but we can do this with just Pathname if we want to (I'm open either way):
```ruby …
```
=> Fix unneccessary removal in eject theme task

bullet_train/docs/upgrades.md, bullet_train/docs/upgrades/options.md, bullet_train/docs/upgrades/yolo-130.md, bullet_train/docs/upgrades/yolo-140.md, bullet_train/docs/upgrades/yolo.md
Fixes #470 
Related to #529 & https://github.com/bullet-train-co/bullet_train/pull/968
This is currently a "forward looking" PR that is making some assumptions about a future state of affairs. I'm assuming that we'll end up merging #529 & https://github.com/bullet-train-co/bullet_train/pull/968, and I'm assuming that those will mark the `1.4.0` release.
Once those are merged (and once we're a little ways down the road, to `1.4.1` and beyond) we'll have a few scenarios that we should cover as far as upgrading:
* Apps currently on `1.2.x` (or earlier) could either
* upgrade to `1.3.0` and then do stepwise upgrades through `1.3.x` until they get to `1.4.0`
* upgrade directly to `1.4.0` and do stepwise from there
* upgrade directly to `latest`
* Apps currently on `1.3.x` could either
* do …
=> Documentation about doing a stepwise upgrade

bullet_train/lib/tasks/bullet_train_tasks.rake
This is a simple fix, but it ensures our gems are correctly checked out when using `bin/hack --link` and `bin/hack --reset`. Otherwise, we get this error:
```
/home/gazayas/.rbenv/versions/3.2.2/lib/ruby/3.2.0/bundler/dsl.rb:49:in `instance_eval':  (Bundler::Dsl::DSLError)
[!] There was an error parsing `Gemfile`: syntax error, unexpected '\n', expecting => - ...t_train-core/bullet_train-super_scaffolding", BULLET_TRAIN_V...
...                              ^
/home/gazayas/work/bt/bullet_train/Gemfile:109: syntax error, unexpected '\n', expecting =>
...rain-api", BULLET_TRAIN_VERSION
...                               ^
/home/gazayas/work/bt/bullet_train/Gemfile:110: syntax error, unexpected '\n', expecting =>
...core/bullet_train-outgoing_webhooks", BULLET_TRAIN_VERSION
... …
```
=> Add gem version to original path for `bin/hack --link`

bullet_train-incoming_webhooks/bullet_train-incoming_webhooks.gemspec, bullet_train-incoming_webhooks/lib/scaffolding/incoming_webhooks_transformer.rb
Joint PR
- https://github.com/bullet-train-co/bullet_train/pull/985
This file ejection logic was working fine when using a local version of `bullet_train-incoming_webhooks`, but the gem doesn't ship with the controller test, so the scaffolder was trying to copy a template that wasn't there. This PR ensures we ship the template so the scaffolder will work properly.
=> Ship controller test for released versions of incoming webhooks gem

.circleci/config.yml
We don't actually use Firefox and we just waste time by installing it. It also seems to cause problems periodically as new versions are released. Removing it will allow us to sidestep those problems.
=> [CI] Install only Chrome and not Firefox in CircleCI

bullet_train/docs/upgrades.md, bullet_train/docs/upgrades/yolo-130.md, bullet_train/docs/upgrades/yolo-140.md
I didn't write a review on #532, but I read through the new documentation to upgrade a personal Bullet Train application I'm working on to 1.4.3, and the process went smoothly 🚀
One thing I noticed was that if you're upgrading to a new version and you have an ejected theme, no merge conflicts arise for those ejected themes because they're originally from `bullet_train-core` and not the starter repository. I struggled for a while trying to find out why my tests weren't passing although everything was working fine on the starter repository. I eventually found out it was because my ejected files hadn't been updated (specifically `_date_and_time.html.erb` and `_date.html.erb` since we updated the daterangepicker logic recently), so I had to manually copy and paste the contents from …
=> Update the upgrading documentation concerning ejected views

bullet_train/docs/upgrades/yolo-130.md, bullet_train/docs/upgrades/yolo-140.md
Fixes https://github.com/bullet-train-co/bullet_train-core/issues/540
This will minimize the chances for unintended updates to gems that don't have a version specified in `Gemfile`.
=> Change `bundle update` => `bundle install` in upgrade instructions

bullet_train-themes/app/views/themes/base/attributes/_days_ago.html.erb
This allows you to control what is displayed in the event that the date attribute in question is blank.
For instance, if you wanted to have a single instance of `days_ago` that would dispaly "Not even once" when the `selected_at` attribute is blank you could call the partial like this:
```erb
<%= render 'shared/attributes/days_ago',
attribute: :selected_at,
default_message: "Not even once"
%>
```
(The `global.never` translation string will be used if a `default_message` is not explicitly passed in.)
Fixes https://github.com/bullet-train-co/bullet_train-core/issues/560
=> Add a `default_message` option to the `days_ago` attribute partial

bullet_train/app/controllers/concerns/account/teams/controller_base.rb, bullet_train/app/views/account/teams/_form.html.erb, bullet_train/config/locales/en/teams.en.yml
This doesn't close #231 because that one deals with a foreign key issue with Memberships, but this at least sets us up so we can delete teams. If we're okay with this, I'll try to figure out the foreign key issue too.
Joint PR
- https://github.com/bullet-train-co/bullet_train/pull/1023
=> Add Delete Team button

bullet_train/app/controllers/concerns/account/teams/controller_base.rb, bullet_train/app/models/concerns/teams/base.rb
Joint PR
- https://github.com/bullet-train-co/bullet_train/pull/1027
I feel much better adding this `RemovingLastTeamException` class (refer to [this comment](https://github.com/bullet-train-co/bullet_train-core/pull/570#discussion_r1334145101))
In the comment in Discord linked in #231 there was the following code which the developer had placed in their Membership model:
```ruby
before_destroy do  
Membership.where(added_by_id: self.id).update_all(added_by_id: nil)       
end
```
This, however, was before we implemented any Team deletion logic, so instead of calling this for every Membership that's being deleted, I just call the `before_destroy` callback once in the Team model instead.
cc/ @brennanlawrence Tagging you in case you had any better suggestions, or if there were any underlying …
=> Fix Membership foreign key constraint for Team deletion, refactor Team deletion logic

bullet_train-themes-light/app/views/showcase/engine/_head.html.erb
Fixes https://github.com/bullet-train-co/showcase/issues/75
Now it looks like this:
=> Display Bullet Train version in Showcase

bullet_train-themes-light/lib/tasks/application.rb, bullet_train/lib/bullet_train/resolver.rb
Closes #576.
I know there's duplicate code here, but we don't currently use the `eject` logic that lives within `BulletTrain::Resolver` when ejecting an entire theme (the ejection logic [there](https://github.com/bullet-train-co/bullet_train-core/blob/4a5818ed1b10893ddf1ebd8198fdb91269610932/bullet_train-themes-light/lib/tasks/application.rb#L6) is all inline).
=> Eject showcase preview when ejecting partials

bullet_train/docs/upgrades.md, bullet_train/docs/upgrades/yolo.md
This will result in a more conservative set of modifications to `Gemfile.lock` and will minimize unexpected updates or other gems.
=> Fix docs to use `bundle install` instead of `bundle update`

bullet_train-super_load_and_authorize_resource/bullet_train-super_load_and_authorize_resource.gemspec
Adds an explicit declaration of the `bullet_train-super_load_and_authorize_resource` gem dependency on `cancancan`.
=> Explicitly declare cancancan dependency for bullet_train-super_load_and_authorize_resource gem

bullet_train-themes-light/lib/tasks/application.rb, bullet_train/lib/bullet_train/resolver.rb
This PR refactors the showcase partial lookup logic as per @kaspth's [comment](https://github.com/bullet-train-co/bullet_train-core/pull/579#discussion_r1339416134) in #579.
I also have a question after looking at the starter repository.
Say we eject a custom theme with `rake bullet_train:themes:light:eject[foo]`. All of the partials that show up in the application are ejected to `app/views/themes/foo`. However, when we eject the showcase files, they get ejected to `app/views/showcase` and don't show up within the `foo` theme. Is this what we want? Do we want the showcase partials to be theme-specific?
=> Refactor showcase partial lookup when ejecting files

bullet_train/docs/upgrades.md, bullet_train/docs/upgrades/notable-versions.md, bullet_train/docs/upgrades/options.md, bullet_train/docs/upgrades/yolo-130.md, bullet_train/docs/upgrades/yolo-140.md
Sometimes we release a version that will require downstream devs to do something, or we might release something that has the potential to conflict with downstream development. In such cases we need to have a place to let developers know what to do.
=> Add documentation about notable versions

bullet_train/app/models/concerns/memberships/base.rb, bullet_train/app/models/concerns/records/base.rb, bullet_train/app/models/concerns/teams/base.rb
We inserted load hooks in https://github.com/bullet-train-co/bullet_train-core/pull/335, and then used them in https://github.com/bullet-train-pro/bullet_train-billing/pull/19
We've shipped releases with that new code, so we can remove our inline backing code from here.
=> Remove now unneeded inline billing support code.

bullet_train/docs/upgrades/notable-versions.md
Just a bit of extra detail to help people resolve conflicts that might arise when upgrading to 1.5.0.
=> [docs] Add a note about merge conflicts in 1.5.0

bullet_train-api/app/helpers/api/open_api_helper.rb
Sets `"$ref"` values to `"$ref": "#/components/schemas/TeamAttributes"` instead of `"$ref": "#/components/schemas/team"` recursively.
Also handles deep schema names such as `"$ref": "#/components/schemas/orders/invoices/line_item` -> `"$ref": "#/components/schemas/OrdersInvoicesLineItemAttributes`.
=> Fix: ref did not have Attributes suffix

bullet_train-super_load_and_authorize_resource/app/controllers/concerns/bullet_train/loads_and_authorizes_resource.rb, bullet_train-super_load_and_authorize_resource/test/controllers/concerns/bullet_train/loads_and_authorizes_resource_test.rb, bullet_train-super_load_and_authorize_resource/test/controllers/concerns/loads_and_authorizes_resource_test.rb, bullet_train-super_load_and_authorize_resource/test/test_helper.rb
This PR does the following:
* `BulletTrain::LoadsAndAuthorizesResource#regex_to_remove_controller_namespace` to a class method to match expectations in `BulletTrain::LoadsAndAuthorizesResource.account_load_and_authorize_resource`.
* Simplifies `BulletTrain::LoadsAndAuthorizesResource.model_namespace_from_controller_namespace`.
* Simplifies and adds some checks against undefined dependencies `BulletTrain::LoadsAndAuthorizesResource#load_team`.
* Adds some tests around these methods.
=> Some more refactoring and testing of BulletTrain::LoadsAndAuthorizesResource

bullet_train-super_scaffolding/bullet_train-super_scaffolding.gemspec, bullet_train-themes-light/bullet_train-themes-light.gemspec, bullet_train/Gemfile.lock, bullet_train/bullet_train.gemspec
bullet_train-super_scaffolding and bullet_train-themes-light are the gems that use masamune-ast,
it doesn't seem like it's a fit in bullet_train itself.
I found this while working on https://github.com/bullet-train-co/bullet_train-core/pull/597, where I had to add this:
```ruby
gem "masamune-ast" # TODO: Move the bullet_train.gemspec dependency to super_scaffolding's gemspec.
```
Ref: https://github.com/bullet-train-co/bullet_train-core/pull/597/files#diff-68cca28f9c2368a9481c0ade06f7da3d4c5c13dd81597e53201ece7c00c8fa90R14
Technically, it means that users could run into require errors if they these libs without the bullet_train, however unlikely.
=> Move masamune ast dependency to using gems

bullet_train-super_scaffolding/lib/scaffolding/script.rb
The PR for testing super scaffolding of Addresses (https://github.com/bullet-train-co/bullet_train/pull/986) landed right before the PR for automatically generating a migration during super scaffolding (https://github.com/bullet-train-co/bullet_train-core/pull/547). As a result a bug / test-failure crept in.
https://app.circleci.com/pipelines/github/bullet-train-co/bullet_train/2585/workflows/1d20bad0-bcad-45f3-96e3-9ac377eec600/jobs/13420?invite=true#step-115-1450_67
The `Address` model `belongs_to :addressable`, which means that the relation is stored on the `Address` side, and not on the owning model. So that means that when we super scaffold an address field it turns out that we don't need to represent that in the migration for the model that will own the address.
=> Bug fix for super scaffolding an address_field

bullet_train-api/bullet_train-api.gemspec, bullet_train/config/locales/en/memberships.en.yml
In [trying to update to Rails 7.1.0](https://github.com/bullet-train-co/bullet_train/pull/1064) we're seeing some test failures like this:
```
Error:
Api::OpenApiControllerTest#test_OpenAPI_document_is_valid:
ActionView::Template::Error: undefined method `deep_stringify_keys' for "{:type=>:object, :title=>\"Teams\", :description=>\"Teams\", :required=>[\"id\", \"name\"], :properties=>{\"id\"=>{:type=>:integer, :description=>\"Team ID\"}, \"name\"=>{:type=>:string, :description=>\"Team\"}, \"time_zone\"=>{:type=>[:string, \"null\"], :description=>\"Primary Time Zone\"}, \"locale\"=>{:type=>[:string, \"null\"], :description=>\"Language\"}, \"created_at\"=>{:type=>[:string, \"null\"], :format=>\"date-time\", :description=>\"Signed Up At\"}, \"updated_at\"=>{:type=>[:string, \"null\"], …
```
=> Bump `jbuilder-schema` to `2.4.0`

bullet_train-super_scaffolding/lib/scaffolding/script.rb
Closes #603.
I tried using `spawn`, `IO.popen` and `trap` as @kaspth suggested in the issue, but couldn't quite get it to work. What I decided to do was wait for the process to end, then compare `git status` before running `bin/rails generate model` and after running it.
Now we get the following if the model exists:
```
> rails g model Foo team:references title:string
invoke  active_record
create    db/migrate/20231006051223_create_foos.rb
create    app/models/foo.rb
invoke    test_unit
create      test/models/foo_test.rb
invoke      factory_bot
create        test/factories/foos.rb
> bin/super-scaffold crud Foo Team title:text_field
Generating Foo model with 'bin/rails generate model Foo team:references title:string'
The name 'Foo' is either already used in your application or reserved by …
```
=> Stop Super Scaffolding if model already exists

bullet_train/config/locales/en/memberships.en.yml
When updating to Rails 7.1.0 we started seeing a new error about a missing translation:
```
Error:
Api::OpenApiControllerTest#test_OpenAPI_document_is_valid:
ActionView::Template::Error: Translation missing: en.memberships.fields.user_profile_photo_id.heading
app/views/api/v1/memberships/_membership.json.jbuilder:1
bullet_train-api (1.6.1) app/helpers/api/open_api_helper.rb:62:in `automatic_components_for'
app/views/api/v1/open_api/index.yaml.erb:20
bullet_train-api (1.6.1) app/controllers/api/open_api_controller.rb:12:in `index'
bullet_train (1.6.1) app/controllers/concerns/controllers/base.rb:95:in `set_locale'
test/controllers/api/open_api_controller_test.rb:10:in `block in <class:OpenApiControllerTest>'
```
This PR adds that translation.
=> Add a missing translation

bullet_train-roles/lib/generators/bullet_train/roles/install/install_generator.rb, bullet_train-roles/lib/roles/support.rb
This PR adds support for the `Trilogy` adapter for roles.
There are several cases where BT interprets the database connection name to check for a MySql database adapter in order to use different syntax to communicate with the database.
=> Support Trilogy MySql Adapter

bullet_train-themes-light/lib/tasks/application.rb
Fixes #613.
This is hard to test locally because released gem paths look like `bullet_train-themes-light-1.6.3` when local gems don't have the version number. This should work though.
=> Show relative path when ejecting showcase partials

bullet_train-super_scaffolding/bullet_train-super_scaffolding.gemspec, bullet_train-super_scaffolding/lib/scaffolding/routes_file_manipulator.rb, bullet_train-themes-light/bullet_train-themes-light.gemspec, bullet_train-themes-light/lib/tasks/application.rb
Masamune now uses [Prism nodes](https://github.com/gazayas/masamune-ast/pull/60), so I feel much safer using this as an interface for other parts of Bullet Train.
Before getting to those other parts though, I wanted to update what we already have in place first. This PR takes care of that.
=> Update to Masamune 2.0.2

bullet_train/lib/bullet_train/resolver.rb
```
> bin/resolve shared/fields/field --eject
```
This yields a file that ends with `/_field.html.erb ` and there's no showcase partial for this, but the following showcase file was getting ejected to the starter repository:
```
app/views/showcase/previews/field_partials/_address_field.html.erb
```
The reason was that the `address_field.html.erb` matches the `end_with?` that I changed here.
=> Fix showcase partial lookup when ejecting a file

bullet_train-super_scaffolding/lib/bullet_train/super_scaffolding/scaffolders/crud_field_scaffolder.rb, bullet_train-super_scaffolding/lib/bullet_train/super_scaffolding/scaffolders/crud_scaffolder.rb, bullet_train-super_scaffolding/lib/bullet_train/super_scaffolding/scaffolders/join_model_scaffolder.rb, bullet_train/docs/getting-started.md, bullet_train/docs/super-scaffolding/sortable.md
This just makes some documentation and help text match our current functionality.
Fixes https://github.com/bullet-train-co/bullet_train-core/issues/625
=> Remove `rails g model` suggestions from `bin/super-scaffolding` help text

bullet_train-api/lib/bullet_train/api/example_bot.rb
Joint PR: https://github.com/bullet-train-co/bullet_train/pull/965
This PR makes it so that we use `FactoryBot.build` when generating example records in `ExampleBot`.
Doing this so that we don't have to actually create live records, clone them, rollback, then reset primary keys. Doing all of that work is slow so it's best to avoid doing it. (And having to reset primary keys for something that we expect to be a normal thing kind of gives me the willies.)
=> Use `build` in ExampleBot instead of `create` + `rollback`

bullet_train-api/bullet_train-api.gemspec
We seem to be having problems in CI where we're not getting a consistent version for `jbuilder-schema`. So this is an attempt to make sure we get the (currently) latest version. We may need to do some more work to make sure this stays in sync with what the gems & starter repo expect. (Does it need to be a first-class dependency that we list in `Gemfile` of the starter repo?)
=> Try to pin jbuilder-schema to a version

bullet_train-api/bullet_train-api.gemspec
This gem is floating to the latest version in CI, and the latest version has a bug. So for now I'm locking it down.
We need to get the `jbuilder-schema` repo set up to pull down the starter repo and run it's test suite as part of the CI process for `jbuilder-schema`. We really need to catch these things before we release a new version instead of after.
=> Lock jbuilder-schema to a known good version

bullet_train-api/.gitignore, bullet_train-api/Gemfile, bullet_train-api/Gemfile.lock, bullet_train-api/bullet_train-api.gemspec, bullet_train-fields/Gemfile, bullet_train-has_uuid/Gemfile.lock, bullet_train-incoming_webhooks/Gemfile, bullet_train-incoming_webhooks/Gemfile.lock, bullet_train-incoming_webhooks/bullet_train-incoming_webhooks.gemspec, bullet_train-integrations-stripe/Gemfile, bullet_train-integrations-stripe/Gemfile.lock, bullet_train-integrations/Gemfile.lock, bullet_train-obfuscates_id/Gemfile.lock, bullet_train-outgoing_webhooks/.gitignore, bullet_train-outgoing_webhooks/Gemfile, bullet_train-outgoing_webhooks/Gemfile.lock, bullet_train-scope_validator/bullet_train-scope_validator.gemspec, bullet_train-sortable/Gemfile, bullet_train-sortable/Gemfile.lock, bullet_train-super_scaffolding/.gitignore, bullet_train-super_scaffolding/Gemfile, bullet_train-super_scaffolding/Gemfile.lock, bullet_train-super_scaffolding/bullet_train-super_scaffolding.gemspec, bullet_train-themes-light/Gemfile, bullet_train-themes-light/Gemfile.lock, bullet_train-themes-tailwind_css/Gemfile, bullet_train/Gemfile, bullet_train/Gemfile.lock, bullet_train/bullet_train.gemspec
In the course of [trying to be able to run all of the tests for individual gems in CI](https://github.com/bullet-train-co/bullet_train-core/pull/569) I've discovered that we don't specify all of our dependencies fully.
In the starter repo the problems don't appear because all of the things that we need end up being dependencies of something or other, but when we try to run tests for individual gems we'll get errors about unsatisfied dependencies.
There are only a few gems where we needed to declare a missing dependency in the `.gemspec`. And those are the only things in this PR that could have the chance to impact downsteam apps.
All of the changes to `Gemfile` and `Gemfile.lock` in each gem won't impact gem consumers at all. They just come into play in local development and CI. The …
=> [CI] Be more explicit about some dependencies

bin/bump-all
This will make it so that `Gemfile.lock` in each gem stasy up to date as we release new versions.
=> [release process] Update lock files when we update gems

bullet_train-fields/Gemfile, bullet_train-fields/Gemfile.lock
This ensures that when we're running tests in CI for the `bullet_train-fields` gem that it's using the peer version of `bullet_train` instead of whichever released version happens to be in `Gemfile.lock`.
=> [CI] Use local copies of the `bullet_train` gem when testing `-fields`

bullet_train/app/models/concerns/memberships/base.rb
For whatever reason, I suddenly ran into issues - the transactional versions of the callbacks weren't triggered anymore when adding/removing a team member.
I think we should be fine with the ordinary versions though. Sorry for the hassle!
=> Don't use _commit callbacks when sending quantity updates

bullet_train-super_scaffolding/lib/scaffolding/routes_file_manipulator.rb, bullet_train-super_scaffolding/test/lib/scaffolding/routes_file_manipulator_test.rb
I don't ever remember a time when this was actually being used, so I think we can safely remove this. It is worth noting that this is different from `@divergent_namespaces` which is *not* commented out.
=> Remove `divergent_namespaces`

bullet_train-super_scaffolding/lib/scaffolding/routes_file_manipulator.rb
Trying piece by piece to migrate to Masamune, and I'm really liking that we can find block ends with Prism nodes. There's one model whose routes are not being properly scaffolded though, so I'll keep trying to debug this one.
I added a TODO, but I also noticed we use both strings and symbols in the `namespaces` array we're passing to this method, which is having an affect on the keys for the hash we're returning. We don't have to do it in this PR, but it might be beneficial to standardize on one or the other.
=> Use Prism nodes to find namespaces in RoutesFileManipulator

.github/workflows/_run_super_scaffolding_tests.yml, .github/workflows/_run_tests.yml, .github/workflows/_starter_repo_tests.yml, .github/workflows/ci.yml
This makes it so that we run the test suites from the starter repo in GitHub Actions.
CircleCI is giving us trouble (again!), so it may be time to ditch it for this repo.
=> [CI] Run starter repo tests in GitHub Actions

bullet_train/app/models/concerns/teams/base.rb
Joint PR: https://github.com/bullet-train-co/bullet_train/pull/1207
Since models are evaluated once at the beginning of a test run this conditional was making it impossible to toggle the value for `HIDE_THINGS` during testing. I think that removing the conditional should be safe since the `Scaffolding::AbsolutelyAbstract::CreativeConcept` model and table are always present.
=> [CI] Handle HIDE_THINGS differently in tests

bullet_train-super_scaffolding/lib/scaffolding/routes_file_manipulator.rb
Closes #690.
The code looks simple now, but this was a really difficult one for me to figure out. One of the most important parts is how we shift elements off of the `namespaces` array to populate the `results` hash.
The new code is the same as the original in that it shifts the first element to `results`, and then leaves any leftover elements in `namespaces` if they don't match any namespaces in the routes file's lines.
I can't say I'm entirely sure *why* we need to shift off lines like this. I want to look over this file as a whole and apply Prism nodes where possible, so I hope to sit down with this file longer to get a better grasp of it.
=> Find namespaces in the `RoutesFileManipulator` with Prism nodes

.github/workflows/version-bump.yml
In order to get the CI workflow to run after we create the upgrade PR we need to create the PR using a PAT. (Weird GitHub Actions rules... 🤷)
=> Use a PAT for generating the upgrade PR

bullet_train/docs/field-partials.md, bullet_train/docs/field-partials/file-field.md, bullet_train/docs/getting-started.md, bullet_train/docs/modeling.md, bullet_train/docs/namespacing.md, bullet_train/docs/oauth.md, bullet_train/docs/super-scaffolding.md, bullet_train/docs/super-scaffolding/delegated-types.md, bullet_train/docs/super-scaffolding/options.md, bullet_train/docs/super-scaffolding/sortable.md, bullet_train/docs/webhooks/incoming.md
Takes care of the documentation task in #662.
I decided to leave the usage text in the old scaffolders as-is because I figured we could just delete it altogether when we get rid of `bin/super-scaffold` (I added a deprecation warning in https://github.com/bullet-train-co/bullet_train/pull/1203).
=> Update documentation for `rails generate super_scaffold`

bullet_train-super_load_and_authorize_resource/app/controllers/concerns/bullet_train/loads_and_authorizes_resource.rb
* Makes some exception messages less wordy
* Simplifies the way we turn a single argument into an array
* Simplification of a conditional
From https://github.com/bullet-train-co/bullet_train-core/pull/525
=> Refactor loads and authorize resource part 1

bullet_train-super_load_and_authorize_resource/app/controllers/concerns/bullet_train/loads_and_authorizes_resource.rb
From #525 
Hoist main options into keyword arguments instead of extracting them from the options hash.
Support both old and new call structures:
```
account_load_and_authorize_resource :project, through: :team # New
account_load_and_authorize_resource :project, :team # Old
```
The deprecate notice TODO was added over 2 years ago, but Bullet Train shifted away from deprecating the `through:` version. https://github.com/bullet-train-co/bullet_train-core/commit/c5ba33bc770ca69a2a05a84f656cd36ed8dac2d8
=> Refactor loads and authorizes resource part 2

bullet_train-super_load_and_authorize_resource/app/controllers/concerns/bullet_train/loads_and_authorizes_resource.rb
Simplifies the process of getting the class name(s) of the `through` association(s).
From #525
=> Refactor loads and authorize resource part 3

.standard.yml, bullet_train-super_load_and_authorize_resource/app/controllers/concerns/bullet_train/loads_and_authorizes_resource.rb
Replace `eval` with direct setting of variables and/or `instance_variable_set` as appropriate.
From #525
Also closes #525.
=> Refactor loads and authorize resource part 5

bullet_train-api/app/helpers/api/open_api_helper.rb
Right now whatever users write in their custom `_paths.yaml.erb` files is added at the end of an appropriate
model's `paths:` section. This leads to duplications if they want to customise the existing endpoint. Those duplications are perceived as an error in Redocly parser.
This PR makes contents of those custom _paths files merge with the main generated yaml. This makes it possible not only to add or override the whole endpoint, but also to add or customise only some particular attributes of the schema.
For example, to add new query property to a route users can simply write:
```yaml
"/contacts":
get:
parameters:
- name: filter
in: query
required: false
style: deepObject
explode: true
schema:
type: object
properties:
email_address:
type: array
items:
type: string
id:
type: array
items: …
```
=> Fix: Customise existing paths in `openapi.yaml`

bullet_train/lib/bullet_train/resolver.rb
Closes #727.
This one is a little tricky because these assets can exist in ejected themes, or in `bullet_train-themes-#{theme_name}` gems. I set things up so all the developer has to do is pass the file name. If we're okay with this, I can add some documentation and mark the PR as ready for review.
=> `bin/resolve` for JavaScript and CSS files

bullet_train-api/Gemfile.lock, bullet_train-fields/Gemfile.lock, bullet_train-incoming_webhooks/Gemfile.lock, bullet_train-integrations-stripe/Gemfile.lock, bullet_train-outgoing_webhooks/Gemfile.lock, bullet_train-sortable/Gemfile.lock, bullet_train-super_scaffolding/Gemfile.lock, bullet_train-themes-light/Gemfile.lock, bullet_train-themes-tailwind_css/Gemfile.lock, bullet_train/Gemfile, bullet_train/Gemfile.lock, bullet_train/app/helpers/account/markdown_helper.rb, bullet_train/bullet_train.gemspec
Follow up to https://github.com/bullet-train-co/bullet_train-core/pull/398#issuecomment-1675575807
CommonMarker has shipped 1.0 and are on 1.0.4, Dependabot has already updated the starter repo: https://github.com/bullet-train-co/bullet_train/pull/1261
So we can require >= 1.0 and remove our fallback now.
=> Remove CommonMarker 0.x fallback

bullet_train-fields/app/javascript/controllers/fields/emoji_picker_controller.js
=> Emoji picker: Properly unregister on disconnect()

bullet_train-api/app/helpers/api/open_api_helper.rb, bullet_train-api/app/views/api/v1/open_api/invitations/_paths.yaml.erb, bullet_train-api/app/views/api/v1/open_api/shared/_paths.yaml.erb, bullet_train-api/app/views/api/v1/open_api/teams/_paths.yaml.erb, bullet_train-api/app/views/api/v1/open_api/users/_paths.yaml.erb
We need to add descriptions to the generated yaml for `automatic_paths_for` sections.
I've added translation keys, falling back to the default text. By doing this in the template, the super-scaffold transformer will correctly pick up the default text to change the correct text for the model if nothing is defined in the l10n files.
I've used the keys `<model_name>.api.paths.<action>.description` to let us define the desired text.
While here, I've changed the summary text to use `<model_name>.api.paths.<action>.summary` so this can be modified in the same way if desired.
Happy to hear suggested alternative ways of doing this, but this works well for our app.
I've also added basic `description`s to the user & team paths too.
=> Add description to generated api paths

bullet_train-api/app/helpers/api/open_api_helper.rb
This PR allows custom properties for components in Open-API schema:
```ruby
<%= automatic_components_for Team, attributes: {add: {password: {type: :string, description: "Test", required: true, example: "password-ABC"}}, remove: :time_zone}, parameters: {add: {password: {type: :string, description: "Test", required: true, example: "password-ABC"}}, remove: :time_zone} %>
<%= automatic_components_for User, attributes: {remove: [:email, :time_zone]}, parameters: {remove: [:email, :time_zone, :locale]} %>
<%= automatic_components_for Membership, attributes: {remove: :team_id}, parameters: {remove: :user_first_name} %>
<%= automatic_components_for Webhooks::Outgoing::Endpoint, attributes: {only: [:id, :team_id]}, parameters: {only: :url} %>
```
Acceptable keys: `add`, `remove` and `only` …
=> Feature: Allow custom properties for components

bullet_train-api/app/helpers/api/open_api_helper.rb, bullet_train-api/bullet_train-api.gemspec, bullet_train-api/config/locales/en/platform/access_tokens.en.yml, bullet_train-api/config/locales/en/platform/applications.en.yml, bullet_train-api/lib/tasks/bullet_train/api_tasks.rake, bullet_train-integrations-stripe/config/locales/en/integrations/stripe_installations.en.yml, bullet_train-integrations-stripe/config/locales/en/oauth/stripe_accounts.en.yml, bullet_train-outgoing_webhooks/config/locales/en/webhooks/outgoing/deliveries.en.yml, bullet_train-outgoing_webhooks/config/locales/en/webhooks/outgoing/delivery_attempts.en.yml, bullet_train-outgoing_webhooks/config/locales/en/webhooks/outgoing/endpoints.en.yml, bullet_train-outgoing_webhooks/config/locales/en/webhooks/outgoing/events.en.yml, bullet_train-super_scaffolding/lib/scaffolding/transformer.rb, bullet_train/config/locales/en/addresses.en.yml, bullet_train/config/locales/en/invitations.en.yml, bullet_train/config/locales/en/memberships.en.yml, bullet_train/config/locales/en/teams.en.yml, bullet_train/config/locales/en/users.en.yml, bullet_train/docs/field-partials.md
This PR introduces separate translations for API: `api_title` and `api_description`. Those are to be used in OpenAPI documentation without affection of the UI.
- Adds those fields to Super Scaffolding;
- Updates translations in core gems;
- Adds rake task `bullet_train:api:create_translations` which updates existing locale files, and creates backup translation files in `tmp/backup_locales` if the original file was updated.
=> Introduce separate translations for API documentation

bullet_train/docs/action-models.md
Was working on https://github.com/bullet-train-pro/bullet_train-action_models/issues/97 and found out the documentation was incorrect.
=> Fix typo in Action Model documentation

bullet_train-fields/Gemfile.lock
Closes #752.
According to the [comment](https://github.com/bullet-train-co/bullet_train-core/issues/752#issuecomment-1914053850) I left there, the dependencies for `bullet_train` needed to be updated so I ran the following in `bullet_train-fields` to account for what was skipped in the process of merging #675 and its surrounding PRs:
```
bundle update --source bullet_train
```
=> Update `bullet_train` for fields gem

bullet_train-themes-light/bullet_train-themes-light.gemspec
This fixes the following error, where even within a released gem, `postcss-import-config.js` isn't found (ie. it's not just related to CI).
```
bin/theme:63:in `<top (required)>': Sorry, we couldn't find `/postcss-import-config.js` in any of the following paths: /Users/pascallaliberte/Projects/bullet-train-co/bullet_train, /Users/pascallaliberte/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bullet_train-themes-light-1.6.29 (RuntimeError)
```
=> add postcss-import-config to gem files

.github/workflows/_run_super_scaffolding_tests.yml
The location of the super scaffolding tests in the starter repo changed with this PR: https://github.com/bullet-train-co/bullet_train/pull/1311
This updates the GitHub workflow to point to the new location.
=> Fix CI for super scaffolding tests

bullet_train-super_scaffolding/lib/scaffolding/class_names_transformer.rb
I was looking over the `ClassNamesTransformer` and wasn't quite sure what this method was doing, so I added an explanation so we won't have to dig in the future to find out what's going on.
I also wonder if there is some way to refactor `replacement_for` later on in the file since there are a lot of string literals there, but I think we can do that in another PR.
=> Add comment to method in `ClassNamesTransformer`

bullet_train-super_scaffolding/app/views/account/scaffolding/absolutely_abstract/creative_concepts/_index.html.erb, bullet_train-super_scaffolding/app/views/account/scaffolding/completely_concrete/tangible_things/_index.html.erb
Whenever Action Models is enabled, we give the user the option to select multiple records of the same model if two or more exist. This happens regardless if the model has an action model that performs actions on it, but I think we should only scaffold the following if the action model requires it:
```erb
<%= render 'shared/bulk_action_select' %>
```
I think that's a separate issue that would require more work, but for now with this PR, I just simply changed `many?` to `any?` because I think the `TargetsMany` action should target records >=1, but we currently have it set so `Select Multiple` is only visible when two or more records exist. Even if user intends to create many records in the future, this means that we can't perform the action at all when just one record is present. Currently …
=> Enable bulk action select when one record is present to perform Action Model actions

bullet_train-super_scaffolding/lib/bullet_train/super_scaffolding/scaffolders/oauth_provider_scaffolder.rb, bullet_train-super_scaffolding/lib/scaffolding/script.rb
Closes #626.
I've set things up so the command will exit if the `--skip-migration-generation` flag is passed but the models haven't been defined:
```
We could not find the following models:
Oauth::SpotifyAccount
Integrations::SpotifyInstallation
Webhooks::Incoming::Oauth::SpotifyAccountWebhook
🚨 Before doing the actual Super Scaffolding, you'll need to generate the models like so:
rails generate model Oauth::SpotifyAccount uid:string data:jsonb user:references
rails generate model Integrations::SpotifyInstallation team:references oauth_spotify_account:references name:string
rails generate model Webhooks::Incoming::Oauth::SpotifyAccountWebhook data:jsonb processed_at:datetime verified_at:datetime oauth_spotify_account:references
However, don't do the `rake db:migrate` until after you …
```
=> Run migrations automatically for the `oauth_provider` scaffolder

bullet_train/app/controllers/concerns/account/controllers/base.rb
instead of looking up `Billing::ControllerSupport`, which lead to false positives: 
when disabling billing in CI (via removing the `STRIPE_SECRET_KEY` or `PADDLE_SECRET_KEY` env variable), this would send me in an infinite redirect loop.
I can't think of any case where it would make sense _not_ to use the `billing_enabled?` helper method here, maybe I'm overlooking something?
=> Check if billing_enabled? before enforcing billing requirements

bullet_train-themes-light/app/views/showcase/engine/_head.html.erb
Closes https://github.com/bullet-train-co/showcase/issues/82.
I have the details written there, but basically we don't need a listener for the `DOMContentLoaded` event since `turbo:load` is fired during the initial page load.
=> Remove excess event listener for `template` tag in showcase view

bullet_train-api/app/helpers/api/open_api_helper.rb
Closes #763 
This PR introduces 2 new methods in `OpenApiHelper`:
- `external_doc "<file_name>"`: Includes external markdown file found in `app/views/api/<version>/open_api/docs`
- `documentation_for <Model>`: Includes external markdown found in file `app/views/api/<version>/open_api/docs/<Model.name.underscore>_description.md`
This allows including external markdown files in OpenAPI schema like in this example:
````yaml
openapi: 3.1.0
info:
...
description: <%= external_doc "info_description" %>
...
tags:
- name: Team
description: <%= description_for Team %>
- name: Addresses::Country
description: <%= description_for Addresses::Country %>
...
````
supposing the following files exist:
````
app/views/api/v1/open_api/docs/info_description.md …
```
=> Feature: Auto-include external markdown files in OpenAPI `index.yaml.erb`

bullet_train-themes-light/app/helpers/application_helper.rb, bullet_train-themes-light/app/helpers/theme_helper.rb, bullet_train/docs/themes/on-jumpstart-pro-projects.md, bullet_train/docs/themes/on-other-rails-projects.md
Context: https://discord.com/channels/836637622432170028/1214513818093228032
This doesn't account for the use of `BulletTrain::Themes::Light` in the public layout, but it should take care of the `current_theme` definition issue.
=> Move current theme definition to `ApplicationHelper` in light theme gem

bullet_train-themes-light/app/views/showcase/previews/partials/_team.html.erb
On the demo site this page takes more than 15 seconds to load becuase there are over 17k `Membership` records in the database. This PR limits it to showing just 10.
=> Don't render all teams in showcase

bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/fields/_address_field.html.erb
Ensure dependent field updates on address are contained to the correct turbo frame.
Currently we're using the parent form to set the selector on the dependent fields. This is an issue if we want multiple address fields on the one model.  This changes the selector to use the `address_form` so it's scoped down to just the individual address in question.  With this change the javascript all does the right thing when changing countries on different addresses within the same form.
While this change doesn't immediately make it possible to add multiple address it seems like good hygiene to keep things appropriately scoped.  And it's fairly trivial to add an `address_type` column to the Address model in applications that require multiple addresses on the same model.
=> Update _address_field.html.erb fixes #809

bullet_train-themes-light/app/views/themes/light/_box.html.erb
Only add the extra div if pagy object exists and we're actually going to show the pagy nav.
Currently if we pass is a pagy object but there's only 1 page of objects, we end up with extra blank space at the bottom of the box.
=> Update shared/box view

bullet_train-sortable/app/javascript/controllers/sortable_controller.js, bullet_train-sortable/package.json, bullet_train-sortable/yarn.lock
Fixes https://github.com/bullet-train-co/bullet_train/issues/1420
Changes `sortable_controller.js` to use `window.jQuery` instead of `$`, define it if missing.
=> Fix "$ is not defined in sortable_controller"

bullet_train-themes/app/views/themes/base/attributes/_number.html.erb
As per https://github.com/bullet-train-co/bullet_train-core/issues/817
This supports both passing the name of the rails helper and giving it additional parameters, as follows:
```
<%= render 'shared/attributes/number', attribute: :input_tokens, format_helper: "number_to_delimited", format_helper_args: { delimiter: '/' } %>
```
=> Enable support of number formatting in shared/attributes/number

bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/fields/_buttons.html.erb, bullet_train/docs/field-partials/buttons.md
In https://github.com/bullet-train-co/bullet_train-core/pull/633 we standardized the way that we pass various options to various field partials. It looks like we had some confusion about whether we were using `buttion_field_options` or `button_field_buttons` as the new variable name. We were using both in difference spots, but they didn't agree so it just didn't work.
This PR standardizes on `button_field_options` to match the pattern that we're using in other field partials. It removes `button_field_buttons`. Also updates the docs to use `button_field_options` instead of just `options`.
Fixes https://github.com/bullet-train-co/bullet_train-core/issues/815
=> Bug fix for passing options to the `buttons` field partial

.github/workflows/_run_super_scaffolding_tests.yml, .github/workflows/_starter_repo_tests.yml, .github/workflows/push.yml, .github/workflows/version-bump.yml
We've updated the starter repo to use version 4 of `yarn` and to get that to work it requries running `corepack enable` prior to running the `setup-node` action.
=> Enable corepack in CI

bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/fields/_date_and_time_field.html.erb
This started happening when I updated to tag v1.7.4
If there is no timezone set on a Team (my `db:reset` did not set one by default) then checking `ActiveSupport::TimeZone.find_tzinfo(current_team_time_zone)` fails with
```
TZInfo::InvalidTimezoneIdentifier at /account/model/:id/new 
Invalid identifier: nil
```
Trace:
Also, I don't see where `user_tz` is being used, but we do things like `<% if current_user&.time_zone != current_team_time_zone %>` when that should maybe be the `user_tz` calculated above. (I didn't know if that's part of this issue or not and I don't have time to dig in more now.)
=> date_and_time_field partial handles no timezone set on team

bullet_train/docs/field-partials/dynamic-forms-dependent-fields.md
I was following the example on this docs page: https://bullettrain.co/docs/field-partials/dynamic-forms-dependent-fields
I couldn't figure out why my Stimulus controller wasn't being called, and I noticed that the input element didn't have any data attributes. I saw that there was a bug in the documentation - data needs to be nested inside the options hash, otherwise it is ignored.
=> Fixed bug in /docs/field-partials/dynamic-forms-dependent-fields.md - data must be nested under options

bullet_train/app/views/account/onboarding/user_details/edit.html.erb
We recently remove the global `jQuery` alias `$` in an effort to work towards eliminationg jquery completely. This PR changes the timezone detection that happens when we edit user details to not rely on jQuery at all, global or otherwise.
Fixes: https://github.com/bullet-train-co/bullet_train/issues/1504
=> Fix: Don't rely on jquery when detecting user timezone

bullet_train-super_scaffolding/lib/scaffolding/attribute.rb, bullet_train-super_scaffolding/lib/scaffolding/script.rb, bullet_train-super_scaffolding/lib/scaffolding/transformer.rb
Fixes: https://github.com/bullet-train-co/bullet_train/issues/1456
Fixes: https://github.com/bullet-train-co/bullet_train/issues/1507
This makes it so that if someone super scaffolds a field that ends with `_id` but does not explicitly include a `class_name` option then we'll try to guess the `class_name` based on the name of the field (instead of throwing a cryptic error).
For instance if you do this:
```
rails g super_scaffold Task Team event_id:super_select
```
We'll guess that `event_id` is a reference to the `Event` class. If we can find an `Event` class in your app then everything proceeds as if you had done this:
```
rails g super_scaffold Task Team event_id:super_select{class_name=Event}
```
If we can't find an `Event` model then you'll get a message saying so and telling you …
=> Better handling in super scaffolding for `_id` fields that don't incldue a `class_name` option

bullet_train-super_scaffolding/lib/bullet_train/super_scaffolding/scaffolders/crud_scaffolder.rb, bullet_train-super_scaffolding/lib/bullet_train/super_scaffolding/scaffolders/join_model_scaffolder.rb, bullet_train-super_scaffolding/lib/scaffolding/script.rb
Fixes: https://github.com/bullet-train-co/bullet_train/issues/1457
Previously superscaffolding commands would hang indefinitely if you tried to geneate a model that has a namespace that exactly matches an existing class.
Now we'll detect that problem and will show you a message letting you know that you need to deconflict the namespace.
```
$ rails generate super_scaffold:join_model InputItem::PromptExecution prompt_execution_id{class_name=PromptExecution} input_item_id{class_name=InputItem}
It looks like the namespace you gave for this model conflicts with an existing class: InputItem
You should use a namespace that doesn't clobber an existing class.
We reccomend using the pluralized version of the existing class.
For instance instead of InputItem use InputItems
```
=> Raise an error if a namespaced model would clobber an existing class

bullet_train-super_scaffolding/lib/bullet_train/super_scaffolding.rb, bullet_train-super_scaffolding/lib/generators/super_scaffold/action_models/performs_export/USAGE, bullet_train-super_scaffolding/lib/generators/super_scaffold/action_models/performs_export/performs_export_generator.rb, bullet_train-super_scaffolding/lib/generators/super_scaffold/action_models/performs_import/USAGE, bullet_train-super_scaffolding/lib/generators/super_scaffold/action_models/performs_import/performs_import_generator.rb
As we transitioned to using generators we somehow dropped support for these two ActionModels.
This is just a quick and dirty PR to get things working. There may be additional options we should add (or existing options we should remove) in the future as these get used.
=> Add generators for `PerformsExport` and `PerformsImport`

bullet_train-api/README.md, bullet_train-api/app/helpers/api/open_api_helper.rb
If an API controller has a separate set of update params defined in the StrongParameters module (using the naming convention `<model>_update_params`), the OpenAPI schema generator will auto-detect and use those parameter for that schema.
=> use _update_params if defined for API schema gen

bullet_train-api/app/helpers/api/open_api_helper.rb, bullet_train-api/lib/bullet_train/api/example_bot.rb
Doc generation currently fails if a model class has singleton methods defined since Rails cache doesn't support caching for those classes.
This skips caching for those models.
=> Fix schema gen for classes with singleton methods

bullet_train-super_scaffolding/lib/bullet_train/super_scaffolding/scaffolders/join_model_scaffolder.rb, bullet_train-super_scaffolding/lib/scaffolding/attribute.rb, bullet_train-super_scaffolding/lib/scaffolding/class_names_transformer.rb, bullet_train-super_scaffolding/lib/scaffolding/transformer.rb
Fixes the association naming problem in: https://github.com/bullet-train-co/bullet_train/issues/1508
I'm going to create a separate issue about the incorrect `valid_` method that's added on one side of the association.
=> Fix association names when scaffolding join models if they don't match the table name

.github/workflows/_run_super_scaffolding_tests.yml
We made some changes to how super scaffold tests in the starter repo are run here: https://github.com/bullet-train-co/bullet_train/pull/1541
This PR just upates the core repo to do the same thing.
=> Update super scaffolding workflow to match the starter repo

bullet_train/app/views/account/onboarding/user_details/edit.html.erb
This PR fixes a couple of problems with detecting and setting the users timezone during sign up.
1.  It updates the select2 instance to reflect the underlying data. For some reason select2 was showing the right thing if you reloaded the `user_details/edit` page, but not when the page first loaded after creating an account.
2.  It makes it so that the event listener that sets the timezone is registered to only be run once. Previously after signing up you'd see errors in the console as you navigated to other pages. The errors were due to the timezone detection function being run on pages where the expected DOM elements were missing.
Fixes: https://github.com/bullet-train-co/bullet_train/issues/1504
=> Fixes for automatically setting user timezone during sign up

bullet_train/docs/action-models.md
Fixes: https://github.com/bullet-train-co/bullet_train-core/issues/857
This whole page about ActionModels could stand to be robustified quite a bit. But for now this at least makes it so that we're mentioning a couple of action types that had previously been completely missing.
=> Add documentation about `PerformsImport` & `PerformsExport`

bullet_train-super_scaffolding/lib/scaffolding/transformer.rb
In https://github.com/bullet-train-co/bullet_train/pull/1207 we changed how the template controller test is structured. But we didn't updated the super scaffolder to accomodate the change in structure.
Since we no longer wrap the entire test in `unless scaffolding_things_disabled?` now we don't need to remove the indentation that was previously there due to that conditional.
Fixes https://github.com/bullet-train-co/bullet_train/issues/1519
=> Fix indentation on controller test generated by super scaffolding

bullet_train/app/views/account/two_factors/create.js.erb, bullet_train/app/views/account/two_factors/destroy.js.erb, bullet_train/app/views/account/two_factors/verify.js.erb, bullet_train/app/views/devise/sessions/pre_otp.js.erb, bullet_train/docs/authentication.md
Fixes https://github.com/bullet-train-co/bullet_train/issues/1555
Fixes https://github.com/bullet-train-co/bullet_train/issues/1556
The files in `bullet_train/app/views/account/two_factors/` still rely on a global `jQuery` object.
I tried to change them from this pattern:
```javascript
jQuery("#two-factor").html("<%= j render partial: "devise/registrations/two_factor"%>");
```
To this pattern:
```javascript
document.querySelector("#two-factor").innerHtml = "<%= j render partial: "devise/registrations/two_factor"%>";
```
But after I did that clicking the "Enable" button in the MFA setup area just didn't do anything. Not sure why.
=> Bug fix for `devise-two-factor` missing `$` and some documentation robustification

bullet_train-themes-light/app/assets/stylesheets/light/tailwind/dark-mode.css
Fixes #849 
Adds missing the styling for the link dialog in `dark-mode.css`.
Before:
After:
=> Fix Trix link dialog in dark mode

bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/fields/_options.html.erb
Fixes #871
Changes to use `options[:id]` instead of undefined `html_options[:id]`
=> Fix `options` partial when `options[:multiple]`

bullet_train-themes/app/views/themes/base/attributes/_html.html.erb
Previously we were manually adding a `div.trix-content` element but we only needed to do that because we didn't have a file in place that is created when you run `rails action_text:install`. I've added that file in the starter repo, where devs would normally expect to find it, so we don't need to manually add the div anymore.
https://github.com/bullet-train-co/bullet_train/pull/1583/files#diff-77f493605c04a022c76dff16f1eca94e25e08854d33261e06ea0d7144302bf74
=> Remove a redundant `.trix-content` div

bullet_train-themes/app/views/themes/base/attributes/_attribute.html.erb
I would love to pass `attribute` down to the theme's `attributes/_base` partial.
That would allow for more versatile _strategies_ to be crafted.
=> Pass attribute down to _base partial

bullet_train-fields/app/javascript/controllers/fields/file_field_controller.js, bullet_train-fields/app/javascript/controllers/fields/file_item_controller.js, bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/attributes/_file.erb, bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/attributes/_files.erb, bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/fields/_file_field.html.erb, bullet_train-themes-tailwind_css/config/locales/en/fields.en.yml
This PR makes a few improvements to the `file_field` partial.
* Wording of the buttons now more closely matches what the button will actually do. For instance, if you've already selected a file to upload instead of saying "Select Another File" the button connected to the file upload element will now say "Select A Different File" to indicate that you're replacing the previously selected file instead of adding to it.
* Once you've selected one or more files we'll now show you the name of the file(s) that will be uploaded.
* Now there's a "Cancel" button for each file that will be uploaded to allow you to change your mind after making the selection.
* After clicking the "Remove Current Document" button we'll now continue to show the name of the file, but will also show a "Cancel Removal" …
=> Improve file fields with the `multiple` option

bullet_train-super_scaffolding/lib/scaffolding/attribute.rb, bullet_train-super_scaffolding/lib/scaffolding/script.rb, bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/fields/_active_storage_image.html.erb, bullet_train-themes/app/views/themes/base/attributes/_images.html.erb
This allows you to pass the `{multiple}` option when super scaffolding image fields **IF** you're using ActiveStorage and not Cloudinary.
If you have Cloudinary activated you'll see something like this:
```
$ rails g super_scaffold Widget Team name:text_field images:image{multiple} single_image:image
You have Cloudinary enabled and tried to scaffold an image field with the `multiple` option.
At this time we do not support multiple images in a single Cloudinary image attribute.
We hope to add support for it in the near future.
For now you could use individual named image attributes, or you might try disabling Cloudinary and using ActiveStorage.
```
Note: I pointed this PR into #886 because the `file_field` and `active_storage_image` field partials share the same Stimulus controller, so we …
=> Enable scaffolding of image fields with the `multiple` option for ActiveStorage

bullet_train-super_scaffolding/lib/generators/super_scaffold/conversations/USAGE, bullet_train-super_scaffolding/lib/generators/super_scaffold/conversations/conversations_generator.rb
This makes it so that you can generate Conversations with the new form (`rails g super_scaffold:conversations`) instead of the old form (`bin/super-scaffold conversations`).
Fixes: https://github.com/bullet-train-pro/bullet_train-conversations/issues/1
=> Add generator for Conversations

bullet_train-themes-light/app/views/themes/light/fields/_field.html.erb, bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/fields/_buttons.html.erb, bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/fields/_date_and_time_field.html.erb, bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/fields/_date_field.html.erb, bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/fields/_option.html.erb, bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/fields/_options.html.erb
This makes it so that most fields will display differently if they are disabled.
Mostly fixes: https://github.com/bullet-train-co/bullet_train-core/issues/573
For comparison I added `options: {disabled: true}` to all the inputs on the TangibleThing form.
Before:
After:
We still need to address the following field types:
* `color_picker`
* `options` with `multiple: true` (aka checkboxes)
* `super_select`
* `address`
* `trix_editor`
=> Provide a visual indicator when fields are disabled

bullet_train/lib/bullet_train.rb
Fixes https://github.com/bullet-train-co/bullet_train-core/issues/895
Previously we only checked to see if a `primary_key` was set using Rails encrypted credentials files. If it was set via ENV var then ActiveRecord encryption would be enabled, but we'd incorrectly determine that it wasn't enabled. This makes it so that two factor stuff shows up when you've set the keys in the ENV.
=> Make `two_factor_authentication_enabled?` aware of keys set via ENV vars

bullet_train-fields/app/javascript/controllers/dependent_fields_frame_controller.js
Previously we were clobbering any query params that had been set by a previous update to dependent fields since we relied only on `window.location.href`. This PR makes it so that we retain any query params that were already set (by using `this.element.src` if present) and we just update the one that has changed.
=> Allow dependent fields to work with multiple dependencies

bullet_train-api/Gemfile.lock, bullet_train-api/bullet_train-api.gemspec, bullet_train-fields/Gemfile.lock, bullet_train-incoming_webhooks/Gemfile.lock, bullet_train-integrations-stripe/Gemfile.lock, bullet_train-integrations/Gemfile.lock, bullet_train-outgoing_webhooks/Gemfile.lock, bullet_train-sortable/Gemfile.lock, bullet_train-super_scaffolding/Gemfile.lock, bullet_train-themes-light/Gemfile.lock, bullet_train-themes-tailwind_css/Gemfile.lock, bullet_train-themes/Gemfile.lock, bullet_train/Gemfile.lock, bullet_train/bullet_train.gemspec
There are breaking changes in versions 7 & 8 that we need to spend some time on to make updates. For now I'm just pinning it to version 6 explicitly so that `depfu` doesn't try to upgrade it.
=> Pin pagy to version 6

bullet_train-fields/app/javascript/controllers/dependent_fields_frame_controller.js
If the dependable field is a checkbox, `field.value` won't store the `checked` state of the checkbox, and so the dependent fields frame will always be evaluated to true.
This PR fixes this issue.
=> dependent_fields_frame: fix if toggled by checkbox

bullet_train-themes-light/app/assets/stylesheets/light/application.css
Fixes the display of table rows while dragging, when sortable.
Before:
After:
=> For sortable tables, only show main column when dragging

bullet_train-themes-light/app/views/themes/light/fields/_field.html.erb
* Wrap a div around the label with `.sr-only` applied if `other_options[:hide_label]` is set true. 
This preserves the `label` for screen readers to properly announce.
Joint PR, required for tests to pass:
https://github.com/bullet-train-co/bullet_train/pull/1705
=> accessibility: change hide_label to render the label in a div.sr-only

bullet_train-themes-light/app/views/themes/light/_team.html.erb
As a first step to alleviate issues such as #917, where `current_team` gets set on page load, we can at least disable turbo-prefetch on team switch links.
=> Prevent turbo-prefetch on team switch links

bullet_train/lib/bullet_train.rb
Heroku recently made some changes to how they set the `PATH` ENV var and now it no longer includes `/app/.heroku/` so our previous detection method is broken.
Now we'll look for `ENV['HEROKU_APP_NAME']`.
=> Imporoved Heroku Detection

bullet_train-api/lib/bullet_train/platform/connection_workflow.rb
In Membership::Base a unique constraint of the user_email column was added last year which broke the Zapier's ConnectionWorkflow.
Simply adding user_email when creating the membership fixes this.
=> Fixed issue where Zapier couldn't connect because unique constraint.

bullet_train-fields/app/javascript/controllers/dependent_fields_frame_controller.js
=> dependent_fields_frame: update URL from src of ancestor turbo_frame

bullet_train-incoming_webhooks/test/controllers/webhooks/incoming/bullet_train_webhooks_controller_test.rb, bullet_train-roles/Gemfile.lock, bullet_train-roles/test/lib/models/permit_test.rb, bullet_train-roles/test/lib/models/role_test.rb
When using `def setup` things can behave unpredictably if developers forget to call `super`. Using the `setup do` hook eliminates that problem.
Partial fix for: https://github.com/bullet-train-co/bullet_train/issues/1626
=> Use `setup do` instead of `def setup` in tests

bullet_train-super_scaffolding/lib/scaffolding/routes_file_manipulator.rb, bullet_train-super_scaffolding/test/lib/scaffolding/examples/result_8._rb, bullet_train-super_scaffolding/test/lib/scaffolding/routes_file_manipulator_test.rb
When doing this:
```
bin/rails generate super_scaffold Task Team name:text_field
bin/rails generate super_scaffold Project Team name:text_field
bin/rails generate super_scaffold Projects::Milestone Project,Team name:text_field
bin/rails generate super_scaffold Projects::Milestones::IncludedTask Projects::Milestone,Project,Team task_id:super_select{class_name=Task} details:text_field --sortable
```
We used to incorrectly nest the routes like this:
```ruby
resources :tasks
resources :projects do
scope module: 'projects' do
resources :milestones, only: collection_actions do
scope module: 'milestones' do
resources :included_tasks, only: collection_actions, concerns: [:sortable]
end
end
namespace :milestones do
resources :included_tasks, except: collection_actions, concerns: [:sortable]
end …
```
=> Handle multiple levels of namespace nesting when generating routes

bullet_train-super_scaffolding/lib/bullet_train/super_scaffolding.rb, bullet_train-super_scaffolding/lib/generators/super_scaffold/audit_logs/USAGE, bullet_train-super_scaffolding/lib/generators/super_scaffold/audit_logs/audit_logs_generator.rb
As we transitioned to using generators we didn't include one for AuditLogs.
This is just a quick and dirty PR to get things working. There may be additional options we should add (or existing options we should remove) in the future as these get used.
=> Add a generator for AuditLogs

bullet_train-super_load_and_authorize_resource/app/controllers/concerns/bullet_train/loads_and_authorizes_resource.rb
`model_class_name` doesn't exist in the file anywhere - instead of raising the string exception an undefined local var exception is returned.
This is a super small fix so that the proper error is returned
current:
```
NameError
undefined local variable or method `model_class_name' for class
```
with change:
```
"Your 'account_load_and_authorize_resource' is broken. Tried to reflect on the `team` association of [\"example\"], but didn't find one.
```
=> fix model_class_name variable in exception raise

bullet_train-super_scaffolding/lib/scaffolding/transformer.rb
Ran across this message. This points the message to write us in Discord.
> We weren't able to automatically add your `#{routes_namespace}` routes for you. In theory this should be very rare, so if you could reach out on Slack, you could probably provide context that will help us fix whatever the problem was. In the meantime, to add the routes manually, we've got a guide at https://blog.bullettrain.co/nested-namespaced-rails-routing-examples/ .
=> transformer routes rescue notices: Slack -> Discord

bullet_train/app/views/account/memberships/_index.html.erb
By default BulletTrain ships with `roles.yml` configured such that any user can invite other people to the team with equal or lesser permissions than the inviter has.
If you change the `default` role so that they only have `read` permissions for the `Invitation` model we still show the "Invite a New Team Member" button to people with that role. If you click that button (as a person with the `default` role) then we redirect you back to the dashboard with an error flash message saying that you're not allowed to access that page.
This PR makes it so that we don't show you the button at all if you're not actually allowed to invite people.
Fixes #906
=> Don't show the "invite new team member" button to people who aren't allowed to do that

bullet_train-api/Gemfile, bullet_train-api/Gemfile.lock, bullet_train-has_uuid/Gemfile, bullet_train-has_uuid/Gemfile.lock, bullet_train-incoming_webhooks/Gemfile, bullet_train-incoming_webhooks/Gemfile.lock, bullet_train-integrations-stripe/Gemfile, bullet_train-integrations-stripe/Gemfile.lock, bullet_train-integrations/Gemfile, bullet_train-integrations/Gemfile.lock, bullet_train-obfuscates_id/Gemfile, bullet_train-obfuscates_id/Gemfile.lock, bullet_train-outgoing_webhooks/Gemfile, bullet_train-outgoing_webhooks/Gemfile.lock, bullet_train-scope_questions/Gemfile, bullet_train-scope_questions/Gemfile.lock, bullet_train-sortable/Gemfile, bullet_train-sortable/Gemfile.lock, bullet_train-super_load_and_authorize_resource/Gemfile, bullet_train-super_load_and_authorize_resource/Gemfile.lock, bullet_train-super_scaffolding/Gemfile, bullet_train-super_scaffolding/Gemfile.lock, bullet_train-themes-light/Gemfile, bullet_train-themes-light/Gemfile.lock, bullet_train-themes-tailwind_css/Gemfile, bullet_train-themes-tailwind_css/Gemfile.lock, bullet_train-themes/Gemfile, bullet_train-themes/Gemfile.lock, bullet_train/Gemfile, bullet_train/Gemfile.lock
We use this in tests for some of the gems and this updates all of the gems to be on the latest release `< 2`. This is a stepping stone PR to eventually get us to the latest version of sqlite3 (currently `2.2.0`).
=> Update sqlite3 to verison 1.7.3

bullet_train-api/Gemfile.lock, bullet_train-api/bullet_train-api.gemspec, bullet_train-fields/Gemfile.lock, bullet_train-incoming_webhooks/Gemfile.lock, bullet_train-integrations-stripe/Gemfile.lock, bullet_train-outgoing_webhooks/Gemfile.lock, bullet_train-sortable/Gemfile.lock, bullet_train-super_scaffolding/Gemfile.lock, bullet_train-themes-light/Gemfile.lock, bullet_train-themes-light/app/assets/stylesheets/light/tailwind/components.css, bullet_train-themes-tailwind_css/Gemfile.lock, bullet_train-themes/Gemfile.lock, bullet_train/Gemfile.lock, bullet_train/bullet_train.gemspec
I'm not updating all the way to version 9 because we also use `pagy_cursor` and the latest version (`0.8.0`) is pinned to `pagy` version `< 9`. If I update `pagy` to version 9 it downgrades `pagy_cursor` to `0.2.0`, which is more than 4 years old.
Related issue on `pagy_cursor`: https://github.com/Uysim/pagy-cursor/issues/68
Joint PR in the starter repo: https://github.com/bullet-train-co/bullet_train/pull/1767
In `pagy` version 7 they [changed the default text](https://github.com/ddnexus/pagy/blob/master/CHANGELOG_LEGACY.md#visual-changes-possibly-breaking-testviews) for the "next page" and "previous page" buttons. For simplicity, and to reduce the amount of code that we need to support, we're sticking with the `pagy` defaults. Previously those buttons read `< Prev` and `Next >` and now …
=> Update `pagy` to version 8

bullet_train-themes/app/views/themes/base/attributes/_boolean.html.erb, bullet_train-themes/app/views/themes/base/attributes/_date.html.erb, bullet_train-themes/app/views/themes/base/attributes/_date_and_time.html.erb, bullet_train-themes/app/views/themes/base/attributes/_days_ago.html.erb, bullet_train/config/locales/en/base.yml
Fixes https://github.com/bullet-train-co/bullet_train-core/issues/247
The attribute display for `date`, `date_and_time`, and `boolean_button` did some unexpected things if the attribute in question was empty.
* `boolean_button` would display a label, but no value.
* `date` and `date_and_time` would display the word "Never" but without a label
All of the other attribute type don't display anything if their value is empty.
In order to allow apps to continue to show those values even if they are empty (but now with a label) those attribute partials now accept a `display_when_blank` option. It can be used like this:
```erb
<%= render 'shared/attributes/date', attribute: :date_field_value, display_when_blank: true %>
```
Before:
After, default behavior:
After, passing `display_when_blank: …
=> Better handling for empty values in some attributes

bullet_train-super_scaffolding/lib/scaffolding/file_manipulator.rb
Previously we were looking for exact matches on certain lines in `roles.yml`, so if you had added a trailing comment we'd end up putting things in the wrong spot.
Fixes https://github.com/bullet-train-co/bullet_train/issues/778
=> Allow for comments on key lines in `roles.yml`

bullet_train-api/Gemfile.lock, bullet_train-fields/Gemfile.lock, bullet_train-incoming_webhooks/Gemfile.lock, bullet_train-integrations-stripe/Gemfile.lock, bullet_train-outgoing_webhooks/Gemfile.lock, bullet_train-sortable/Gemfile.lock, bullet_train-super_scaffolding/Gemfile.lock, bullet_train-themes-light/Gemfile.lock, bullet_train-themes-tailwind_css/Gemfile.lock, bullet_train-themes/Gemfile.lock, bullet_train/Gemfile.lock, bullet_train/bullet_train.gemspec
Is this gem actually used anymore? (Was it ever actually used?)
=> Remove dependency on bullet_train-routes

bullet_train-themes-light/app/assets/stylesheets/light/fields/trix_editor.css, bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/fields/_color_picker.html.erb, bullet_train-themes/app/views/themes/base/fields/_trix_editor.html.erb
Makes some progress on https://github.com/bullet-train-co/bullet_train-core/issues/573
This allows `color_picker` fields to be disabled:
As well as `trix_editor` fields:
=> Allow more field partials to be disabled

bullet_train-themes-light/app/assets/stylesheets/light/fields/super_select.css
Fixes: https://github.com/bullet-train-co/bullet_train-core/issues/975
It turns out that we had specifically targeted single super selects with some height related rules to make them the same size as text inputs. Applying the same rules to multiple super selects fixed the problem.
Before:
After:
=> Make super selects a consistent height for single and multiple selects

bullet_train-themes-light/app/assets/stylesheets/light/fields/super_select.css, bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/fields/_address_field.html.erb
This allows you to pass `options: {disabled: true}` to disable the entire address field.
Like this:
```erb
<%= render 'shared/fields/address_field', method: :address_value, options: {disabled: true} %>
```
It disabled every input that's a part of the address, regardless of whether the address has been populated previously.
Empty initial state:
With a previously populated address:
This finally fixes #573
=> Allow address fields to be disabled

.github/workflows/_starter_repo_tests.yml
This is purely an internal change for the CI workflow for the `core` repo. It shouldn't affect Bullet Train apps at all.
=> Tweak parallelization in GitHub Actions

bullet_train-themes-light/app/views/themes/light/actions/_action.html.erb
**Error it fixes:**
action_models.scheduled_for shows the following error: missing interpolation argument :for in "Scheduled for %{for}" ({:post_name=>"Post", :posts_possessive=>"Post’s", :team_name=>"dev", :teams_possessive=>"dev’s", :at=>"December 28 at 12:00 AM"} given)
**When:**
An action with SupportScheduling concern and at when an explicit scheduled_for datetime is set in the future at action creation time.
**Reproduce:**
rails generate super_scaffold Post Team scheduled_at:date_and_time_field
rails generate super_scaffold:action_models:targets_one ScheduledPost Post Team 
Then on the UI:
- create a new Post
- create a scheduled action with a date in the future
=> Fix expected parameter for action_models.scheduled_for

bullet_train-super_scaffolding/lib/scaffolding/transformer.rb, bullet_train/docs/super-scaffolding.md, bullet_train/docs/super-scaffolding/targets.md
Imagine you Super Scaffold a `Project` resource:
```
rails generate super_scaffold Project Team name:text_field
```
And then you open the `Project` model, and remove all of the target comments:
```ruby
class Project < ApplicationRecord
belongs_to :team
validates :name, presence: true
end
```
And then you want to Super Scaffold a `file_field` onto `Project`.
```
rails generate super_scaffold:field Project documents:file_field{multiple}
```
Previously we would act like everything had gone according to plan, but in reality we wouldn't have updated the `Project` model with some important changes.
```
rails generate super_scaffold:field Project documents:file_field{multiple}
Adding new fields to Project with 'bin/rails generate migration add_documents_to_projects documents:attachments' …
```
=> Warn the user if we can't find target hooks for super scaffolding

bullet_train-api/app/controllers/api/v1/platform/access_tokens_controller.rb, bullet_train-outgoing_webhooks/test/models/concerns/webhooks/outgoing/uri_filtering_test.rb, bullet_train-super_load_and_authorize_resource/app/controllers/concerns/bullet_train/loads_and_authorizes_resource.rb
Some of the billing gems don't have an `index` or `show` method, but they use `account_load_and_authorize_resource`, which assumes that all CRUD methods are always present on controllers that ues it.
This adds those template methods so that we don't throw an error when accessing those controller in dev and test environments.
Related to: https://github.com/bullet-train-co/bullet_train-core/pull/930
=> Add more template methods

bullet_train/app/javascript/controllers/desktop_menu_controller.js
Previously if you clicked somewhere inside the user menu, without clicking on an actual link it would effectively lock the menu into an open state with no way to close it.
This makes it so that a click outside the menu will close it.
Fixes https://github.com/bullet-train-co/bullet_train-core/issues/987
=> Allow user menu to be closed after a click inside it

bullet_train/app/views/devise/mailer/unlock_instructions.html.erb
missing `=` to render the text
=> fix unlock email body rendering

bullet_train/config/routes.rb
Previously if you tried to declare a public root route (without a unique `as:` reference) you'd get an `ArgumentError` saying:
```
Invalid route name, already in use: 'root'
```
Similary if you tried to declare an account scoped dashboard route (with an `as: 'dashboard'` reference) you'd get an `ArgumentError` saying:
```
Invalid route name, already in use: 'account_dashboard'
```
Both of these errors were happening when we tried to draw default routes after the application had already declared them.
Now we resuce the `ArgumentError` and check the message to see if it's a complaint about a duplicate route. If so, we do nothing and let the app use the route defined in the primary `config/routes.rb` file.
Fixes https://github.com/bullet-train-co/bullet_train/issues/1656
=> Allow applications to declare their own root routes

bullet_train-api/Gemfile.lock, bullet_train-fields/Gemfile.lock, bullet_train-incoming_webhooks/Gemfile.lock, bullet_train-integrations-stripe/Gemfile.lock, bullet_train-integrations-stripe/bullet_train-integrations-stripe.gemspec, bullet_train-integrations-stripe/lib/bullet_train/integrations/stripe.rb, bullet_train-integrations/app/controllers/concerns/account/oauth/omniauth_callbacks/controller_base.rb, bullet_train-outgoing_webhooks/Gemfile.lock, bullet_train-sortable/Gemfile.lock, bullet_train-super_scaffolding/Gemfile.lock, bullet_train-themes-light/Gemfile.lock, bullet_train-themes-tailwind_css/Gemfile.lock, bullet_train-themes/Gemfile.lock, bullet_train/Gemfile.lock, bullet_train/bullet_train.gemspec
This switches out a dependency for Stripe Connect.
We used to use `omniauth-stripe-connect` but it hasn't been updated in quite sometime and it's pegged to versions of `ominauth` on the `1.x` line. Unfortunately the `1.x` line of ominauth has some security vulnerabilities. In order to update `omniauth` to the `2.x` line we're moving to `omniauth-stripe-connect-v2` which is basically the same as `omniauth-stripe-connect` but with a `.gemspec` that allows `omniauth` versions `~> 2.0`.
This also bumps the version of `omniauth-rails_csrf_protection` to `~> 1.0` so that it works with the new stripe connect gem.
The docs for all of the new versions are the same as the docs for the old versions, so there shouldn't be any application changes required. I've tested these in my local starter repo …
=> Update stripe connect and omniauth gems

bullet_train-api/Gemfile.lock, bullet_train-fields/Gemfile.lock, bullet_train-has_uuid/Gemfile.lock, bullet_train-incoming_webhooks/Gemfile.lock, bullet_train-integrations-stripe/Gemfile.lock, bullet_train-integrations/Gemfile.lock, bullet_train-obfuscates_id/Gemfile.lock, bullet_train-outgoing_webhooks/Gemfile.lock, bullet_train-roles/Gemfile, bullet_train-roles/Gemfile.lock, bullet_train-roles/README.md, bullet_train-roles/bullet_train-roles.gemspec, bullet_train-scope_questions/Gemfile.lock, bullet_train-sortable/Gemfile.lock, bullet_train-super_load_and_authorize_resource/Gemfile.lock, bullet_train-super_scaffolding/Gemfile.lock, bullet_train-themes-light/Gemfile.lock, bullet_train-themes-tailwind_css/Gemfile.lock, bullet_train-themes/Gemfile.lock, bullet_train/Gemfile, bullet_train/Gemfile.lock
Previously we had pinned some of the gems to use a fork of `active_hash` via the `Gemfile` in the gem. But the `.gemspec` files pointed to a real, published version of the gem. The starter repo also points to the published version.
This PR removes the pins that point at the fork, and is sets an appropriate version constraint for `active_hash` in the appropriate `.gemspec`.
Fixes https://github.com/bullet-train-co/bullet_train-core/issues/1029
=> Remove pins of `active_hash` that point to a fork

bullet_train-api/Gemfile.lock, bullet_train-fields/Gemfile.lock, bullet_train-incoming_webhooks/Gemfile.lock, bullet_train-integrations-stripe/Gemfile.lock, bullet_train-outgoing_webhooks/Gemfile.lock, bullet_train-sortable/Gemfile.lock, bullet_train-super_scaffolding/Gemfile.lock, bullet_train-themes-light/Gemfile.lock, bullet_train-themes-tailwind_css/Gemfile.lock, bullet_train-themes/Gemfile.lock, bullet_train/Gemfile.lock, bullet_train/bullet_train.gemspec
We used to include `image_processing` as a hard dependency in the `bullet_train` gem, but we don't use it directly (or even `require` it).
We recommend that people use Cloudinary for handling images, which means that they don't need `image_processing` which is used for handling images with `ActiveStorage`.
If you want to use `image_processing` then you should uncomment the line for it in the `Gemfile` of your Bullet Train application.
Fixes: https://github.com/bullet-train-co/bullet_train-core/issues/1040
=> Remove the `image_processing` gem

bullet_train-api/Gemfile.lock, bullet_train-api/bullet_train-api.gemspec, bullet_train-fields/Gemfile.lock, bullet_train-incoming_webhooks/Gemfile.lock, bullet_train-integrations-stripe/Gemfile.lock, bullet_train-outgoing_webhooks/Gemfile.lock, bullet_train-sortable/Gemfile.lock, bullet_train-super_scaffolding/Gemfile.lock, bullet_train-super_scaffolding/bullet_train-super_scaffolding.gemspec, bullet_train-super_scaffolding/lib/bullet_train/super_scaffolding.rb, bullet_train-themes-light/Gemfile.lock, bullet_train-themes-tailwind_css/Gemfile.lock, bullet_train-themes/Gemfile.lock, bullet_train/Gemfile.lock, bullet_train/bullet_train.gemspec, bullet_train/lib/bullet_train.rb
We had been using both `colorize` and `colorizer` but they both do the same thing. `colorizer` hasn't been touched in 13 years and doesn't even have documentation available, so we're gonna standarize on `colorize`.
If you need to use `colorizer` for some reason you can add it to the `Gemfile` in your application.
Fixes https://github.com/bullet-train-co/bullet_train-core/issues/1043
=> Remove the `colorizer` gem

bullet_train/docs/billing/stripe.md
- Add installation instructions on how to install the open source versions of bullet_train-billing and bullet_train-billing-stripe gems.
- Slightly re-organize instructions to make it easy for a reader to differentiate betwen the paid and open source installation steps
- Expand on the shared installation procedure
- Update instructions on interfacing with the Stripe workbench for product and webhook creation
=> Update Billing documentation

bin/test-core-gems, bullet_train/config/locales/en/framework_packages.yml, bullet_train/docs/upgrades/yolo-130.md
We removed the empty gem in https://github.com/bullet-train-co/bullet_train-core/pull/1031 but there were still a few references to it that we missed. This removes them.
=> Remove lingering references to `bullet_train-scope_questions`

bullet_train-api/Gemfile.lock, bullet_train-fields/Gemfile.lock, bullet_train-incoming_webhooks/Gemfile.lock, bullet_train-integrations-stripe/Gemfile.lock, bullet_train-outgoing_webhooks/Gemfile.lock, bullet_train-sortable/Gemfile.lock, bullet_train-super_scaffolding/Gemfile.lock, bullet_train-themes-light/Gemfile.lock, bullet_train-themes-tailwind_css/Gemfile.lock, bullet_train-themes/Gemfile.lock, bullet_train/Gemfile, bullet_train/Gemfile.lock, bullet_train/bullet_train.gemspec, bullet_train/lib/bullet_train/core_ext/string_emoji_helper.rb
We used to declare `unicode-emoji` as a dependency, but it's only used in one method that we don't seem to actually call anywhere.
That method has been updated to check if `unicode-emoji` is available. If so it will proceed as normal, if not it will raise an error saying that you should add `unicode-emoji` to your `Gemfile`.
We've added `unicode-emoji` to the "optional gems" section of the `Gemfile` in the starter repo, with it being commented out by default.
Fixes https://github.com/bullet-train-co/bullet_train-core/issues/1048
=> Remove `unicode-emoji` as a hard dependency

bullet_train/app/controllers/concerns/account/onboarding/user_details/controller_base.rb
This prevents an error caused by `load_and_authorize_resource` assuming that all controllers that use it implement certain methods.
Fixes https://github.com/bullet-train-co/bullet_train-core/issues/1066
=> Override a template method

bullet_train-api/app/views/account/platform/access_tokens/_form.html.erb, bullet_train-api/app/views/account/platform/applications/_form.html.erb, bullet_train-integrations-stripe/app/views/account/integrations/stripe_installations/_form.html.erb, bullet_train-integrations-stripe/app/views/account/oauth/stripe_accounts/_form.html.erb, bullet_train-outgoing_webhooks/app/views/account/webhooks/outgoing/deliveries/_form.html.erb, bullet_train-outgoing_webhooks/app/views/account/webhooks/outgoing/delivery_attempts/_form.html.erb, bullet_train-outgoing_webhooks/app/views/account/webhooks/outgoing/endpoints/_form.html.erb, bullet_train-super_scaffolding/app/views/account/scaffolding/absolutely_abstract/creative_concepts/_form.html.erb, bullet_train-super_scaffolding/app/views/account/scaffolding/completely_concrete/tangible_things/_form.html.erb, bullet_train/app/views/account/invitations/_form.html.erb, bullet_train/app/views/account/memberships/_form.html.erb, bullet_train/app/views/account/onboarding/invitation_lists/new.html.erb, bullet_train/app/views/account/teams/_form.html.erb, bullet_train/app/views/account/teams/new.html.erb, bullet_train/docs/super-scaffolding/delegated-types.md
although I don't think it removes `local: true` from the super scaffold generator. I am not sure where the `_form.erb.tt` for super scaffold is declared.
=> rm local: true from forms. it's old tech

bullet_train-roles/README.md, bullet_train-roles/lib/roles/permit.rb, bullet_train-roles/test/lib/models/permit_test.rb
This allows a call to `permit` to only create permissions for some of the Roles in the Roles.yml file.
=> Allow a subset of roles to be passed to permit

bullet_train-api/Gemfile, bullet_train-api/Gemfile.lock, bullet_train-api/app/helpers/api/open_api_helper.rb, bullet_train-api/test/dummy/app/views/api/v1/teams/_team.json.jbuilder, bullet_train-api/test/dummy/config/locales/teams.en.yml, bullet_train-api/test/dummy/db/schema.rb, bullet_train-api/test/factories/teams.rb, bullet_train-api/test/helpers/open_api_helper_test.rb, bullet_train-api/test/test_helper.rb
Continue of https://github.com/bullet-train-co/bullet_train-core/pull/1080 with test setup for `api` gem and added tests for `automatic_components_for` helper
I decided to put it in a separate PR in case we have any issues/comments with the test setup or anything else not related to the fix itself.
This way we can merge the fix (https://github.com/bullet-train-co/bullet_train-core/pull/1080) first and tests (this PR) separately.
Or we can just merge this PR only.
✅ Initial fix included
---
PR Description from #1080 (which is included in this PR):
✅ The changes are tested in a real project with docs generation.
This PR allows you to disable a required field for OpenApi generation.
It was previously impossible to do this when a field has a presence validation.
It can be very useful for …
=> Setup and add tests for automatic_components_for helper

bullet_train-fields/package.json, bullet_train-fields/yarn.lock
Uses an inline `node -e` script for copying `node_modules/intl-tel-input/build/js/utils.js` into place for the `copy:intl-tel-input-utils` command.
Closes #1109
=> Replace cp-cli for copy:intl-tel-input-utils script

bullet_train-api/Gemfile.lock, bullet_train-api/app/controllers/concerns/api/controllers/base.rb, bullet_train-api/bullet_train-api.gemspec, bullet_train-api/lib/bullet_train/api.rb, bullet_train-fields/Gemfile.lock, bullet_train-incoming_webhooks/Gemfile.lock, bullet_train-integrations-stripe/Gemfile.lock, bullet_train-outgoing_webhooks/Gemfile.lock, bullet_train-sortable/Gemfile.lock, bullet_train-super_scaffolding/Gemfile.lock, bullet_train-themes-light/Gemfile.lock, bullet_train-themes-tailwind_css/Gemfile.lock, bullet_train-themes/Gemfile.lock, bullet_train/Gemfile.lock
This is the simplest thing I could get to work for removing `pagy_cursor`. Luckily we seem to only use it for one feature, which is an `after` filter. That filter only seems to be used by API clients, and is not used via the UI (we use the standard `page` for `pagy` there). I don't personally use the API in BT for anything, so I'm not sure if there are subtleties in there that I'm missing.
I previously added a test for pagination here: https://github.com/bullet-train-co/bullet_train-core/pull/1131/files
=> Remove `pagy_cursor`

bin/each-gem
Use `system` instead of back ticks so we stream the output.
=> Slight tweak to the `each-gem` script

bullet_train-obfuscates_id/app/models/concerns/obfuscates_id.rb, bullet_train-obfuscates_id/test/models/obfuscates_id_concern_test.rb
This PR fixes a bug where calling `to_param` would raise `can't convert nil into Integer` for non-persisted records.
=> fix: `to_param` for non-persisted records

bullet_train/lib/bullet_train.rb
Issue: https://github.com/bullet-train-co/bullet_train-core/issues/1191
If the api token environment variable is set but the gem is not loaded (or vice versa) we log an error and return false.
=> Add additional checks and warnings to `openai_enabled?`
