- bullet_train/lib/tasks/bullet_train_tasks.rake
Closes #5.
There are still some things I need to figure out so I've opened this up as a draft, but I did want to mention the `--link` and `--reset` flags since I already had that logic written and didn't want to reinvent the wheel so to speak. If we're okay with just using that to link up all the gems then great, if not I'll reference the script you mentioned in the issue.
First thing's first, I'll try to get the initial logic running properly when cloning the core repository.
> Update `bin/hack` for new environment

- bullet_train-themes-light/app/assets/stylesheets/light/tailwind/colors.css
Adds a new color option for themes: green
> (CSS) adds green as an option to theme colors

- bullet_train-super_scaffolding/lib/scaffolding/block_manipulator.rb
- bullet_train-super_scaffolding/test/lib/scaffolding/block_manipulator_test.rb
The same code as https://github.com/bullet-train-co/bullet_train-super_scaffolding/pull/97, moving it here to avoid the merge conflict.
Local unit tests are also working within `bullet_train-super_scaffold` itself.
> Insert multiple lines and handle line breaks in `BlockManipulator`

- .circleci/config.yml
- bin/checkout-and-link-starter-repo
Brings over stuff I learned in https://github.com/bullet-train-co/nice_partials/pull/75
> Speed up CI

- bullet_train/docs/themes.md
While reading the themes doc, saw a couple typos and small formatting clean-up opportunity, so here it is!
> Clean up and minor updates to themes doc

- bullet_train/app/javascript/index.js
- bullet_train/app/javascript/support/turn.js
Joint PR
- https://github.com/bullet-train-co/bullet_train/pull/644
> Import `turn.js` from the starter repository

- bullet_train/app/views/account/teams/_breadcrumbs.html.erb
- bullet_train/config/locales/en/teams.en.yml
https://github.com/bullet-train-co/bullet_train/issues/618
> Fix Breadcrumb for Team Setting

- bullet_train-fields/app/javascript/controllers/fields/super_select_controller.js
- bullet_train-themes/app/views/themes/base/fields/_super_select.html.erb
Fixes https://github.com/bullet-train-co/bullet_train-fields/issues/35
> Super-select: focus on type ahead field on open

- bullet_train/app/helpers/account/forms_helper.rb
> stringify_keys on options returned from options_for helper

- bullet_train-super_scaffolding/app/controllers/account/scaffolding/completely_concrete/tangible_things_controller.rb
Closes https://github.com/bullet-train-co/bullet_train-core/issues/48
Joint PR
- https://github.com/bullet-train-co/bullet_train/pull/598
> Redirect to show page when creating a new record

- bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/fields/_cloudinary_image.html.erb
width & height were duplicated which gave a cloudinary error
> typo regarding preview_image_options

- .circleci/config.yml
- bin/checkout-and-link-starter-repo
Starts us down the path of hopefully having better, easier Bundler caching.
> Tweak CI: use newest Ruby orb

- bullet_train-themes-light/app/views/themes/light/layouts/_devise.html.erb
- bullet_train-themes-light/app/views/themes/light/workflow/_box.html.erb
Fixes https://github.com/bullet-train-co/bullet_train-core/issues/175 .
> Improve the mobile responsiveness of the Devise layout.

- bullet_train/app/views/layouts/docs.html.erb
> Fix bg colors for docs mobile menu

- bullet_train-themes-light/app/views/showcase/previews/partials/_breadcrumb.html.erb
- bullet_train-themes-light/app/views/showcase/previews/partials/_cell.html.erb
- bullet_train-themes-light/app/views/showcase/previews/partials/_decision_line.html.erb
- bullet_train-themes-light/app/views/showcase/previews/partials/_line.html.erb
- bullet_train-themes-light/app/views/showcase/previews/partials/_link_row.html.erb
- bullet_train-themes-light/app/views/showcase/previews/partials/_notices.html.erb
- bullet_train-themes-light/app/views/showcase/previews/partials/_team.html.erb
- bullet_train-themes-light/app/views/showcase/previews/partials/_well.html.erb
- bullet_train-themes-light/app/views/themes/light/menu/_top.html.erb
https://github.com/bullet-train-co/bullet_train-core/issues/174
This PR deals with adding showcase examples for theme partials.
> [WIP] Showcase Example for Theme Partials

- bullet_train-api/bullet_train-api.gemspec
- bullet_train-fields/bullet_train-fields.gemspec
- bullet_train-fields/lib/bullet_train/fields/engine.rb
- bullet_train-super_scaffolding/bullet_train-super_scaffolding.gemspec
- bullet_train-super_scaffolding/lib/bullet_train/super_scaffolding/engine.rb
- bullet_train-themes-light/bullet_train-themes-light.gemspec
- bullet_train-themes-light/lib/bullet_train/themes/light/engine.rb
- bullet_train-themes-tailwind_css/bullet_train-themes-tailwind_css.gemspec
- bullet_train-themes-tailwind_css/lib/bullet_train/themes/tailwind_css/engine.rb
- bullet_train-themes/bullet_train-themes.gemspec
- bullet_train/bullet_train.gemspec
- bullet_train/lib/bullet_train.rb
- bullet_train/lib/tasks/bullet_train_tasks.rake
This reverts commit d2efa595b70f1660fdf7e35b49f22d3845a756be and PR #141.
> Revert "Use `Gem.find_files` in `bt:link`."

- bullet_train/lib/tasks/bullet_train_tasks.rake
- https://github.com/bullet-train-co/bullet_train/pull/743
> Update develop rake task name to hack

- bullet_train-themes-light/lib/tasks/application.rb
Reported by @julianrubisch: https://github.com/bullet-train-co/bullet_train-core/issues/26#issuecomment-1527180613
> Update mailer layout with ejected theme name

- bullet_train-themes-light/app/assets/stylesheets/light/tailwind/utilities/billing.css
- bullet_train-themes-light/app/views/themes/light/layouts/_pricing.html.erb
Continuation of #309.
I changed a couple of the styles, let me know what you think!
@jagthedrummer
Looks like this now with emerald (There are a couple of solid lines around the bg gradient, not sure if we want to change it though)
> Apply application theme colors to pricing layout

- bullet_train-super_scaffolding/lib/scaffolding/transformer.rb
Context: https://discord.com/channels/836637622432170028/1080382156477579264/1080382825792028702
I would be glad to implement this if it's high up on our priority list, but I think I'll try to work on documentation for #151 for the time being. I'm not sure if all of the other options work right now, so I'd only document the flags that are available for our developers to use.
> Comment out help text concerning `--skip-parent`

- bullet_train/docs/field-partials/super-select.md
Closes https://github.com/bullet-train-co/bullet_train-core/issues/190
> Add a note about susper scaffolding to super_select docs

- bullet_train-super_scaffolding/lib/scaffolding/transformer.rb
Related to https://github.com/bullet-train-co/bullet_train/pull/718
> Remove unneeded comment concerning database index length

- bullet_train/docs/field-partials.md
- bullet_train/docs/field-partials/date-related-fields.md
Adding docs now that these two PRs have been merged.
- https://github.com/bullet-train-co/bullet_train-base/pull/44
- https://github.com/bullet-train-co/bullet_train-themes/pull/6
> Add docs for custom `Date` and `DateTime` formats

- bullet_train-themes-light/app/views/themes/light/fields/_field.html.erb
- bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/fields/_buttons.html.erb
- bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/fields/_cloudinary_image.html.erb
- bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/fields/_color_picker.html.erb
- bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/fields/_date_and_time_field.html.erb
- bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/fields/_date_field.html.erb
- bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/fields/_field.html.erb
- bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/fields/_file_field.html.erb
- bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/fields/_option.html.erb
- bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/fields/_options.html.erb
- bullet_train-themes/app/views/themes/base/fields/_ckeditor.html.erb
- bullet_train-themes/app/views/themes/base/fields/_email_field.html.erb
- bullet_train-themes/app/views/themes/base/fields/_emoji_field.html.erb
- bullet_train-themes/app/views/themes/base/fields/_number_field.html.erb
- bullet_train-themes/app/views/themes/base/fields/_password_field.html.erb
- bullet_train-themes/app/views/themes/base/fields/_phone_field.html.erb
- bullet_train-themes/app/views/themes/base/fields/_super_select.html.erb
- bullet_train-themes/app/views/themes/base/fields/_text_area.html.erb
- bullet_train-themes/app/views/themes/base/fields/_text_field.html.erb
Nice Partials has a mechanism to automatically yield into a passed block, so we needn't do this manually.
Some of the work spun off from #159 into smaller chunks.
> Replace remaining explicit yields with Nice Partials' automatic ones.

- bullet_train-themes/app/views/themes/base/fields/_email_field.html.erb
- bullet_train-themes/app/views/themes/base/fields/_password_field.html.erb
- bullet_train/app/views/devise/passwords/new.html.erb
- bullet_train/app/views/devise/registrations/new.html.erb
- bullet_train/app/views/devise/sessions/new.html.erb
> Pass on email_field contents to inner field partial

- bullet_train-themes/app/views/themes/base/fields/_email_field.html.erb
- bullet_train-themes/app/views/themes/base/fields/_password_field.html.erb
- bullet_train/app/views/devise/passwords/new.html.erb
- bullet_train/app/views/devise/registrations/new.html.erb
- bullet_train/app/views/devise/sessions/new.html.erb
Reverts bullet-train-co/bullet_train-core#368
Fixes https://github.com/bullet-train-co/bullet_train-core/issues/370
> Revert "Pass on email_field contents to inner field partial"

- bullet_train/app/views/layouts/docs.html.erb
> Docs: with showcase link

- bullet_train-super_scaffolding/lib/scaffolding/transformer.rb
> Super Scaffold crud-field boolean attributes

- bullet_train-themes-light/app/assets/stylesheets/light/fields/super_select.css
When the application's theme is set to `:emerald`
> Conform super select style to application's theme

- bullet_train-super_scaffolding/lib/bullet_train/super_scaffolding/scaffolders/oauth_provider_scaffolder.rb
Related to #294.
I've personally made the same mistake before, so I wrote clearer instructions so other developers don't run into the same issue.
> Write clearer instructions for the oauth-provider scaffolder

- bullet_train-api/app/views/account/platform/access_tokens/_index.html.erb
- bullet_train-api/app/views/account/platform/access_tokens/show.html.erb
- bullet_train-super_scaffolding/app/views/account/scaffolding/absolutely_abstract/creative_concepts/_index.html.erb
- bullet_train-super_scaffolding/app/views/account/scaffolding/absolutely_abstract/creative_concepts/show.html.erb
- bullet_train-super_scaffolding/app/views/account/scaffolding/completely_concrete/tangible_things/_index.html.erb
- bullet_train-super_scaffolding/app/views/account/scaffolding/completely_concrete/tangible_things/show.html.erb
- bullet_train-super_scaffolding/lib/scaffolding/block_manipulator.rb
- bullet_train-super_scaffolding/lib/scaffolding/transformer.rb
- bullet_train/app/models/concerns/records/base.rb
- bullet_train/app/models/concerns/teams/base.rb
- bullet_train/app/views/account/memberships/_index.html.erb
- bullet_train/bullet_train.gemspec
> Update deprecated Cable Ready methods

- bullet_train-super_scaffolding/lib/scaffolding/transformer.rb
I think I was over-complicating things when I originally wrote this code.
As far as I can tell the tests are passing, so I think we should be fine with simplying this snippet.
> Set true to field option if attribute `is_multiple`

- bullet_train/docs/indirection.md
- bullet_train/lib/tasks/bullet_train_tasks.rake
`rake bullet_train:eject[locales]`
> Eject Locales

- bullet_train/docs/indirection.md
- bullet_train/docs/tunneling.md
- bullet_train/docs/upgrades.md
- bullet_train/docs/zapier.md
After setting up the starter repo, the remote name for starter repo is `bullet-train`.
And I fixed a small typo
> Docs: Update starter repo git remote name

- bullet_train/app/views/account/onboarding/user_details/edit.html.erb
> Add missing notices partial for user details edit page

- bullet_train-super_scaffolding/lib/scaffolding/transformer.rb
Closes https://github.com/bullet-train-co/bullet_train/issues/668.
> Ensure attributes with same name as model get scaffolded

- .github/workflows/release.yml
The workflow file has to exist in the `main` branch before it can be manually run. So I'm going to merge this PR, then continue working in a branch. I'll be able to run the workflow from that branch until it's ready.
> Getting started on a release workflow

- .github/workflows/tag-release.yml
Got the syntax wrong here and couldn't test it until it was in main. Ah, the CI/CD life.
> [release process] Bug fix

- .github/workflows/release.yml
Taking a different stab at this. CI/CD is fun.
> [release process] Auto publish gems & packages when a release is created

- .github/workflows/release.yml
> [release process] Another attempt at auto-publishing gems/packages

- .github/workflows/push.yml
- .github/workflows/version-bump.yml
For now I'm just installing `thor` as part of the workflow, becausue I don't think we want to include it as a dependency.
> [release process] Install `thor` as part of the release workflows

- bullet_train-api/app/controllers/concerns/api/v1/memberships/controller_base.rb
- bullet_train-api/app/views/api/v1/memberships/index.json.jbuilder
- bullet_train-api/app/views/api/v1/memberships/show.json.jbuilder
- bullet_train/config/locales/en/memberships.en.yml
That implements memberships API, adds OpenAPI specs, and fixes path examples generation.
Requires https://github.com/bullet-train-co/bullet_train/pull/725
> Memberships API

- bullet_train/docs/application-options.md
- bullet_train/lib/bullet_train.rb
Closes #272.
Joint PR
- https://github.com/bullet-train-co/bullet_train/pull/791
> Add check to see if developer menu is being skipped

- bullet_train-fields/app/javascript/controllers/fields/file_item_controller.js
- bullet_train-fields/app/javascript/controllers/index.js
- bullet_train-super_scaffolding/lib/scaffolding/transformer.rb
- bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/attributes/_files.erb
- bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/fields/_file_field.html.erb
- bullet_train/docs/field-partials/file-field.md
@ammit Not sure why, but https://github.com/bullet-train-co/bullet_train-core/pull/10 was causing `rails test test/system/super_scaffolding_partial_test.rb` to fail after merging, so I reverted it. This PR was created by reverting the revert PR. :-) 
Example failure at https://app.circleci.com/pipelines/github/bullet-train-co/bullet_train/1507/workflows/2ab93a9a-1645-4b7d-92c6-21e7ed821dbc/jobs/6513
To run this test locally, you have to do some prep steps:
```
bundle add spring
bundle exec test/bin/setup-super-scaffolding-system-test
```
Once you've done that once you can run the following as many times as you like:
```
rails test test/system/super_scaffolding_partial_test.rb:36
```
> Adds multiple file upload

- bullet_train-api/lib/bullet_train/api/example_bot.rb
Calling e.g. address.team= throws an error, if address has_one team through person and person has_one team through company and company belongs_to team so the resulting error will be caught here and a warning logged.
> rescue ExampleBot deep cloning error

- bullet_train-incoming_webhooks/app/models/webhooks/incoming/bullet_train_webhook.rb
- bullet_train/lib/bullet_train/configuration.rb
Closes #454.
Joint PR (Details written there)
- https://github.com/bullet-train-co/bullet_train/pull/899
> Add configuration for incoming webhook parent class

- bullet_train-api/app/views/api/v1/open_api/invitations/_paths.yaml.erb
Closes https://github.com/bullet-train-co/bullet_train/issues/912.
Joint PR with https://github.com/bullet-train-co/bullet_train/pull/915, see main description there.
> Fix: 912 — OpenAPI test failure

- bullet_train/lib/tasks/bullet_train_tasks.rake
> Pass a custom path to bin/hack --link

- bullet_train/config/locales/en/invitations.en.yml
Forgot to remove this in #353.
> Remove unneeded locale

- bullet_train-api/lib/bullet_train/api/example_bot.rb
> Ensure that tables are reset by FactoryBot.example

- bullet_train-super_scaffolding/lib/bullet_train/super_scaffolding/scaffolders/oauth_provider_scaffolder.rb
> Fix OAuth super-scaffold

- bullet_train/docs/heroku.md
Fixes https://github.com/bullet-train-co/bullet_train/issues/125
> [docs] Add warning about Heroku costs

- bullet_train-api/app/controllers/concerns/api/controllers/base.rb
Fixes https://github.com/bullet-train-co/bullet_train-core/issues/408
Fixes https://github.com/bullet-train-co/bullet_train/issues/765
> Set pagination order to be ascending by id

- bullet_train/app/views/layouts/docs.html.erb
Fixes https://github.com/bullet-train-co/bullet_train-core/issues/356
> Add Algolia DocSearch to the demo site documentation

- bullet_train/lib/tasks/bullet_train_tasks.rake
Joint PR: https://github.com/bullet-train-co/bullet_train/pull/968
> Explicitly set the expected verison of BulletTrain gems

- bullet_train-themes-light/app/assets/stylesheets/light/fields/cloudinary_image.css
Fixes https://github.com/bullet-train-co/bullet_train/issues/218
> Small visual fix for Cloudinary uploader

- bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/fields/_option.html.erb
- bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/fields/_options.html.erb
- bullet_train/app/views/account/invitations/_form.html.erb
- bullet_train/app/views/account/memberships/_form.html.erb
Fixes https://github.com/bullet-train-co/bullet_train-core/issues/218
> Make checkboxes use the primary color of the theme

- bullet_train-api/app/controllers/api/open_api_controller.rb
- bullet_train-api/app/helpers/api/open_api_helper.rb
- bullet_train-api/bullet_train-api.gemspec
Fixes
- https://github.com/bullet-train-co/jbuilder-schema/issues/43,
- https://github.com/bullet-train-co/jbuilder-schema/issues/45,
- https://github.com/bullet-train-co/jbuilder-schema/issues/46,
- https://github.com/bullet-train-co/jbuilder-schema/issues/47,
- https://github.com/bullet-train-co/jbuilder-schema/issues/48
> Fix: OpenAPI bugs

- bullet_train-super_scaffolding/lib/scaffolding/script.rb
@pascallaliberte I know #534 is still a draft, but this CLI help text is relatively new so I just wanted to make sure it was covered. You can run this command to check it out in the terminal:
```
bin/super-scaffold --field-partials
```
> Add address_field to field partial help text

- bullet_train-super_scaffolding/bullet_train-super_scaffolding.gemspec
- bullet_train-themes-light/bullet_train-themes-light.gemspec
> Lock down Masamune to the `1.2.x` line

- bin/checkout-and-link-starter-repo
- bin/checkout-and-link-starter-repo-for-core-tests
For some reason all of a sudden GitHub doesn't like us sending a header.
Fixes https://github.com/bullet-train-co/bullet_train-core/issues/616
> [CI] Fix branch matching problem

- bullet_train/docs/field-partials/dynamic-forms-dependent-fields.md
- bullet_train/docs/upgrades/yolo-130.md
* Fix `dependent_fields_frame` partial mention
* Add mention of manual package.json version updates through 1.3.x version updates
> Docs: fix dependent_fields_frame, mention package.json updates in yolo-130.md

- bullet_train-super_scaffolding/lib/scaffolding/routes_file_manipulator.rb
- bullet_train-themes-light/app/views/themes/light/actions/_action.html.erb
Depends on https://github.com/bullet-train-pro/bullet_train-action_models/pull/94
> Scaffold routes properly for deeply nested Action Model actions

- bullet_train-fields/app/helpers/fields/address_field_helper.rb
- bullet_train/docs/field-partials/dynamic-forms-dependent-fields.md
> Update address partial label for United States

- bullet_train-super_scaffolding/lib/bullet_train/super_scaffolding.rb
- bullet_train-super_scaffolding/lib/scaffolding/script.rb
> Show help text if scaffolding type isn't provided to `bin/super-scaffold`

- bullet_train-super_scaffolding/lib/generators/super_scaffold/incoming_webhooks/incoming_webhooks_generator.rb
- bullet_train-super_scaffolding/lib/generators/super_scaffold/join_model/join_model_generator.rb
- bullet_train-super_scaffolding/lib/generators/super_scaffold/oauth_provider/oauth_provider_generator.rb
- bullet_train-super_scaffolding/test/lib/generators/super_scaffold/field_generator_test.rb
- bullet_train-super_scaffolding/test/lib/generators/super_scaffold/incoming_webhooks_generator_test.rb
- bullet_train-super_scaffolding/test/lib/generators/super_scaffold/join_model_generator_test.rb
- bullet_train-super_scaffolding/test/lib/generators/super_scaffold/oauth_provider_generator_test.rb
What I get for trying to do some clean up right before merging a PR. 🤦‍♂️
> Bug fix for super scaffold generators

- bullet_train-api/Gemfile.lock
- bullet_train-fields/Gemfile.lock
- bullet_train-integrations-stripe/Gemfile.lock
- bullet_train-outgoing_webhooks/Gemfile.lock
- bullet_train-scope_questions/Gemfile.lock
- bullet_train-sortable/Gemfile.lock
- bullet_train-super_load_and_authorize_resource/.gitignore
- bullet_train-super_load_and_authorize_resource/Gemfile.lock
- bullet_train-super_scaffolding/Gemfile.lock
- bullet_train-themes-light/Gemfile.lock
- bullet_train-themes-tailwind_css/Gemfile.lock
Each time we relase new versions these lock files will change in CI.
I'll look at making the version bump action handle them.
> [CI] Update lockfiles to latest versions

- bullet_train/lib/bullet_train.rb
Preparing for Paddle Billing support
> Add PADDLE_SECRET_KEY to billing_enabled? check

- bullet_train/app/models/concerns/memberships/base.rb
A minimal instrumentation to notify any subscribing payment provider gems of changed per-seat quantity.
> Publish changed quantity whenever a membership is mutated

- bullet_train-api/Gemfile.lock
- bullet_train-fields/Gemfile.lock
- bullet_train-incoming_webhooks/Gemfile.lock
- bullet_train-integrations-stripe/Gemfile.lock
- bullet_train-outgoing_webhooks/Gemfile.lock
- bullet_train-outgoing_webhooks/bullet_train-outgoing_webhooks.gemspec
- bullet_train-sortable/Gemfile.lock
- bullet_train-super_scaffolding/Gemfile.lock
- bullet_train-super_scaffolding/bullet_train-super_scaffolding.gemspec
- bullet_train-themes-light/Gemfile.lock
- bullet_train-themes-tailwind_css/Gemfile.lock
- bullet_train/Gemfile.lock
- bullet_train/bullet_train.gemspec
Making some more progress on ensuring that the dependencies that we _say_ we need match up with the dependencies that we _actually_ need.
> [CI] Add some more explicit dependencies

- bullet_train-themes-light/app/views/themes/light/_link_row.html.erb
> Fix typo in `_link_row.html.erb`

- bullet_train-themes-light/app/views/themes/light/workflow/_box.html.erb
Fixes #708 
Joint PR: https://github.com/bullet-train-co/bullet_train/pull/1217
> Respect logo_height setting in workflow/box

- bullet_train-themes-light/app/views/themes/light/actions/_action.html.erb
Fixes https://github.com/bullet-train-co/bullet_train-core/issues/651
> Make confusing double conditional less confusing

- bullet_train-super_load_and_authorize_resource/app/controllers/concerns/bullet_train/loads_and_authorizes_resource.rb
Simplify the process of finding the model name/class.
From #525
> Refactor loads and authorize resource part 4

- bullet_train-themes-light/app/views/themes/light/menu/_item.html.erb
- bullet_train/app/views/layouts/docs.html.erb
> Docs: add new-window icons to external links in nav

- bullet_train-themes-light/app/views/themes/light/fields/_field.html.erb
- bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/fields/_field.html.erb
Fixes #756 
From:
https://github.com/bullet-train-co/bullet_train-core/assets/104179/fc9c715f-11ea-46cf-bbe4-4c221790814c
To:
https://github.com/bullet-train-co/bullet_train-core/assets/104179/1173dfb1-7d7d-474a-b7c6-cba73084ae4d
> Fix zoom-in on mobile when tapping on fields

- bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/fields/_date_and_time_field.html.erb
> Fix date_and_time_field when current_user is undefined

- bullet_train-themes-light/app/views/themes/light/layouts/_account.html.erb
Fixes #778.
Here's an example of what it looks like with Creative Concepts
> Set breadcrumb overflow to auto

- bullet_train/app/models/concerns/users/base.rb
Joint PR
- https://github.com/bullet-train-co/bullet_train/pull/1297
> Enable devise lockable by default

- bullet_train/docs/upgrades.md
> Typo in upgrades.md

- bullet_train-api/README.md
- bullet_train-api/bullet_train-api.gemspec
- bullet_train-api/lib/tasks/bullet_train/api_tasks.rake
Here's my attempt to write the `README` for `bullet_train-api` gem.
> Add `README` to `bullet_train-api` gem

- bullet_train-super_scaffolding/lib/scaffolding/transformer.rb
Fixes https://github.com/bullet-train-co/bullet_train/issues/1421
> Super scaffolding fix for `--sortable` with a multi word parent

- bullet_train/docs/upgrades/notable-versions.md
This is a documentation only update.
> Upgrade to 1.5.0 docs use correct path to updates folder

- bullet_train-themes-light/app/views/themes/light/_box.html.erb
Implementation of part 1 of https://github.com/bullet-train-co/bullet_train/issues/1451
> Don't display header if no title or description

- bullet_train-super_scaffolding/lib/scaffolding/transformer.rb
Fixes: https://github.com/bullet-train-co/bullet_train/issues/1482
> Bug fix: Replace `underscore!` with `underscore`

- bullet_train-fields/app/javascript/controllers/fields/cloudinary_image_controller.js
> cloudinary_image_controller: remove jQuery dependency

- bullet_train/docs/heroku.md
Joint PR: https://github.com/bullet-train-co/bullet_train/pull/1525
This makes the documentation match the updates made to `app.json` in that PR.
> Update Heroku docs

- bullet_train-themes/app/views/themes/base/fields/_trix_editor.html.erb
Addresses of the two issues in #870
* trix_editor: only use mentions when current_team.present?
> Fix showcase preview for Trix Editor 

- bullet_train-super_scaffolding/app/views/account/scaffolding/absolutely_abstract/creative_concepts/_index.html.erb
Fixes: https://github.com/bullet-train-co/bullet_train-core/issues/877
> Pass the `pagy` instance to the `box` partial for CreativeConcepts

- bullet_train-themes/app/views/themes/base/attributes/_image.html.erb
Fixes: https://github.com/bullet-train-co/bullet_train/issues/1600
> Don't raise an error when displaying a record with an empty iamge upload

- bullet_train-super_scaffolding/lib/scaffolding/attribute.rb
- bullet_train-super_scaffolding/lib/scaffolding/transformer.rb
Fixes: https://github.com/bullet-train-co/bullet_train/issues/1599
> Scaffold removal boilerplate for ActionStorage images

- bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/fields/_file_field.html.erb
- bullet_train-themes-tailwind_css/config/locales/en/fields.en.yml
- bullet_train/config/locales/en/base.yml
Fixes: https://github.com/bullet-train-co/bullet_train/issues/1657
> Make file fields reference 'files' not 'documents'

- bullet_train-outgoing_webhooks/app/models/concerns/webhooks/outgoing/delivery_support.rb
- bullet_train-outgoing_webhooks/test/models/concerns/webhooks/outgoing/delivery_test.rb
Fix for the issue https://github.com/bullet-train-co/bullet_train-core/issues/921
> Outgoing Webhooks: Fix running the last attempt

- bullet_train/docs/heroku.md
Added some additional explanation for some things as well as instructions for how to generate a "Deploy to Heroku" button for your project if you don't already have one.
> Update the docs for deploying to Heroku

- bullet_train/docs/field-partials/file-field.md
The super scaffolder will make the required changes to the model so we don't need to ask people to do it manually.
> Remove some unnecessary steps from the file field docs

- bullet_train/docs/themes.md
This is a lighter weight option than ejecting an entire theme and tends to be where most people want to start.
> Update theme docs for info on how to change only the colors

- bullet_train-fields/app/helpers/dependent_fields_frame_helper.rb
> Dependent Fields Frame: use send method= in accept_query_string_override_for

- bullet_train-fields/Gemfile
- bullet_train-fields/Gemfile.lock
- bullet_train-themes/Gemfile
- bullet_train-themes/Gemfile.lock
Fixes https://github.com/bullet-train-co/bullet_train-core/issues/752
Fixes https://github.com/bullet-train-co/bullet_train-core/issues/424
> Synchronize version number between all core gems

- bullet_train-api/Gemfile
- bullet_train-api/Gemfile.lock
- bullet_train-incoming_webhooks/Gemfile
- bullet_train-incoming_webhooks/Gemfile.lock
- bullet_train-integrations-stripe/Gemfile
- bullet_train-integrations-stripe/Gemfile.lock
- bullet_train-outgoing_webhooks/Gemfile
- bullet_train-outgoing_webhooks/Gemfile.lock
- bullet_train-sortable/Gemfile
- bullet_train-sortable/Gemfile.lock
- bullet_train-super_scaffolding/Gemfile
- bullet_train-super_scaffolding/Gemfile.lock
- bullet_train-themes-light/Gemfile
- bullet_train-themes-light/Gemfile.lock
- bullet_train-themes-tailwind_css/Gemfile
- bullet_train-themes-tailwind_css/Gemfile.lock
- bullet_train/Gemfile
- bullet_train/Gemfile.lock
Hopefully this catches everything this time.
> Synchronize version number between all core gems - again

- bullet_train/lib/bullet_train.rb
Our previous method of detecting that we're in Heroku required the app to run the following command:
```
heroku labs:enable runtime-dyno-metadata
```
We didn't have that documented anywhere, so new apps often had trouble around Redis. (It's super dumb that Heroku is **still** using janky self-signed certs for their Redis offering.)
This PR iproves our detection method in a number of ways.
First we'll check for the existence of the `BT_IS_IN_HEROKU` ENV var. This can be used to explicitly tell BT whether or not it's in Heroku. We'll set this value to `true` in `app.json` of the Starter Repo. So new apps that are deployed via `app.json` will have this set. This is the safest and most stable method.
Next we'll do the check that we used to do for `HEROKU_APP_NAME`. We're keeping it for …
> Improved Heroku Detection

- bullet_train-themes-light/app/views/showcase/engine/_head.html.erb
Fixes: https://github.com/bullet-train-co/bullet_train-core/issues/908
> Remove duplicate reference to application.css in Showcase

- .github/workflows/_run_super_scaffolding_tests.yml
Joint PR: https://github.com/bullet-train-co/bullet_train/pull/1825
> Use the new method for running super scaffolding tests in the starter repo

- bullet_train/docs/oauth.md
- bullet_train/docs/stripe-connect.md
The starter repo comes with a Stripe Connect integration all ready to go, but it's not documented so it's hard to know how to use it.
This ia  quick and dirty pass at getting _something_ documented so it's not quite so mysterious.
> Add some docs about Stripe Connect

- bullet_train-obfuscates_id/app/models/concerns/obfuscates_id.rb
> support array IDs in obfuscates decode

- bullet_train/app/helpers/account/teams_helper.rb
Fixes https://github.com/bullet-train-co/bullet_train-core/issues/1070
> Bug fix for generating a team avatar when team name is blank

- bullet_train-fields/yarn.lock
- bullet_train-sortable/yarn.lock
- bullet_train/yarn.lock
These only come into play during CI and/or local testing. They don't filter down to applications or the starter repo.
> Update all yarn.lock files

- bullet_train-fields/package.json
- bullet_train-fields/yarn.lock
- bullet_train-sortable/package.json
- bullet_train-sortable/yarn.lock
- bullet_train/package.json
- bullet_train/yarn.lock
Since we release new versions via a GitHub Actions workflow, and it doesn't use `np` I don't think there's any reason to have it in the project.
Fixes https://github.com/bullet-train-co/bullet_train-core/issues/1110
> Remove `np` from all the `package.json` files

- bullet_train/docs/billing/stripe.md
- bullet_train/docs/trademark.md
- bullet_train/docs/upgrades.md
Already updated these on the site, just updating them in the docs as well.
> Fix Discord links.

- bullet_train-api/Gemfile.lock
- bullet_train-api/bullet_train-api.gemspec
- bullet_train-api/test/controllers/concerns/api/controllers/base_pagination_test.rb
- bullet_train-fields/Gemfile.lock
- bullet_train-incoming_webhooks/Gemfile.lock
- bullet_train-integrations-stripe/Gemfile.lock
- bullet_train-outgoing_webhooks/Gemfile.lock
- bullet_train-sortable/Gemfile.lock
- bullet_train-super_scaffolding/Gemfile.lock
- bullet_train-themes-light/Gemfile.lock
- bullet_train-themes-tailwind_css/Gemfile.lock
- bullet_train-themes/Gemfile.lock
- bullet_train/Gemfile.lock
- bullet_train/bullet_train.gemspec
Joint PR: https://github.com/bullet-train-co/bullet_train/pull/2089
> Bump pagy to verison 9

- bin/each-gem
This script allows you to run the same command in each of the sub gem directories in an automated way.
For instance:
```
./bin/each-gem do "bundle update rack --conservative"
```
> Add a convenience script for making bulk gem updates

- bullet_train/docs/webhooks/incoming.md
This updates the docs to include a link to the implementaiton of the signature.
Fixes #1166
> Add a link to the Incoming Webhooks docs

- bullet_train-api/Gemfile.lock
- bullet_train-fields/Gemfile.lock
- bullet_train-has_uuid/Gemfile.lock
- bullet_train-incoming_webhooks/Gemfile.lock
- bullet_train-integrations-stripe/Gemfile.lock
- bullet_train-integrations/Gemfile.lock
- bullet_train-obfuscates_id/Gemfile.lock
- bullet_train-outgoing_webhooks/Gemfile.lock
- bullet_train-roles/Gemfile.lock
- bullet_train-scope_validator/Gemfile.lock
- bullet_train-sortable/Gemfile.lock
- bullet_train-super_load_and_authorize_resource/Gemfile.lock
- bullet_train-super_scaffolding/Gemfile.lock
- bullet_train-themes-light/Gemfile.lock
- bullet_train-themes-tailwind_css/Gemfile.lock
- bullet_train-themes/Gemfile.lock
- bullet_train/Gemfile.lock
```
./bin/each-gem run-command "bundle update thor --conservative"
```
This only affects local development and CI. It does not flow down to starter repo apps.
> Bump thor in all the gems

- .github/workflows/tag-release.yml
GitHub does a really poor job or layout out a workflow, so this will hopefully make it a little better.
> Try to make the release workflow look nicer
